### ISSUE TITLE
link to resource on GBIF.org

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#102]
See https://github.com/gbif/registry-console/issues/65
notice the additional menu item `View on GBIF.org`

![details2 copy](https://user-images.githubusercontent.com/6759267/50336458-8aed4f80-050e-11e9-902e-ae129ff90224.png)

**Comment by luckyluck** [comment]
@MortenHofft, I've added such link for organization, dataset and node. Would you mind to tell me if I need to add link for any other item?

**Comment by MortenHofft** [comment]
Please do so for these as well
collection: https://www.gbif-uat.org/grbio/collection/04672bb4-5621-4b5b-949d-63ceea77ae24
institution: https://www.gbif-uat.org/grbio/institution/80d54b17-d262-41fb-9012-66f6f654efe2
grbio persons: https://www.gbif-uat.org/grbio/person/9190f640-1e26-428a-9075-aec814c74b6d

**Comment by MortenHofft** [comment]
I see the links are absolute: https://github.com/gbif/registry-console/commit/806ff6cd98ee7d13c17d511b50db17e73687d030#r31819070

We have a registry.gbif-dev.org, registry.gbif-uat.org and registry.gbif.org. they should link to www.gbif-dev.org, www.gbif-uat.org and www.gbif.org respectively. for demo registry and others just link to dev.

**Comment by luckyluck** [comment]
@MortenHofft, sorry, I just thought that the list above was full. I'll fix it in a minute.

**Comment by luckyluck** [comment]
Done! Added URL to the config the same way as it is for API.
