### ISSUE TITLE
use suggest endpoint instead of search for autocompletes

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#105]
Nodes suggest
https://registry-demo.gbif-dev.org/node/suggest?q=danb

publisher suggest
https://registry-demo.gbif-dev.org/organization/suggest?q=dan

**Comment by luckyluck** [comment]
@MortenHofft, I added suggest endpoints for Organizations, Nodes, and Datasets. Datasets endpoint should be fixed.
