### ISSUE TITLE
no regex on dois

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#106]
![screen shot 2018-12-21 at 11 15 41](https://user-images.githubusercontent.com/6759267/50337564-ce958880-0511-11e9-9852-e4fb3b650be9.png)

DOIs should be validated

**Comment by MortenHofft** [comment]
I do not remember the rules for validating DOIs I'm afraid. It is not something you can find a formal definition of?

**Comment by MortenHofft** [comment]
from Datacites website: `/^10.\d{4,9}/[-._;()/:A-Z0-9]+$/i`

**Comment by luckyluck** [comment]
> from Datacites website: `/^10.\d{4,9}/[-._;()/:A-Z0-9]+$/i` should match all new and 99% of existing (based on 75 million reference database).
> Similar from crossRef, though they qualify it a bit in this post: https://www.crossref.org/blog/dois-and-matching-regular-expressions/

Sorry, I didn't know that it is a common parameter.
