### ISSUE TITLE
help texts on forms have different font-sizes

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#108]
![screen shot 2018-12-21 at 11 15 20](https://user-images.githubusercontent.com/6759267/50337644-14eae780-0512-11e9-879e-4bfcb229617e.png)

The form and presentation labels have the option to add a (?) with help text. At some point we talked about moving help texts there. Should we do so, or are there argument not to?

con: 
* it is more hidden

pro: 
* it looks cleaner
* the system is mostly for the same few that know the fields
* It is there if you need it and we use (?) for help texts other places. As such it is consistent.

I'm in favour of using the (?) next to the form label for this info.

**Comment by luckyluck** [comment]
@MortenHofft, I added icons with help texts as you proposed. Also, I did the same for IMPORTANT texts using a red icon with an exclamation point. Looks compact. If you agree with this, we can just close this issue.
