### ISSUE TITLE
links in breadcrumb

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#114]
I like being able to navigate by breadcrumb. Especially on mobile

Should we add links so that
`Dataset` links to dataset search. `Title of Dataset 13.12.2018` links to the dataset details. Similar for others.
![screen shot 2018-12-21 at 11 44 42](https://user-images.githubusercontent.com/6759267/50338830-e7a03880-0515-11e9-8d0e-7c70603f1e9a.png)

**Comment by luckyluck** [comment]
@MortenHofft, should we always link Dataset on Search page or we should somehow keep in mind that user came from Deleted or Duplicate list pages?

**Comment by MortenHofft** [comment]
yeah - maybe it will just be confusing, and since the entity is available from visible tabs perhaps we should ignore it.
