### ISSUE TITLE
missing 404s

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#118]
https://gbif-registry-demo.netlify.com/organization/nonsense
shows
![screen shot 2018-12-21 at 12 07 38](https://user-images.githubusercontent.com/6759267/50339896-0fdd6680-0519-11e9-9970-72aa04467a9d.png)

instead of a 404 page

**Comment by MortenHofft** [comment]
404s shows as `new organization`
![screen shot 2019-01-02 at 12 17 05](https://user-images.githubusercontent.com/6759267/50592373-2928d000-0e94-11e9-8cda-76cfe00872d6.png)

**Comment by luckyluck** [comment]
Now the header will be shown during loading and hidden in the case of an exception.
