### ISSUE TITLE
redux vs context for enums

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#12]
I see that enums are distributed via context. What is the reasoning behind introducing context for this? Have you considered using the redux store to hold the enums? Alternatively move the store to context. My initial thought is that I would prefer to have it in one place: redux OR context.

https://github.com/gbif/registry-console/blob/master/src/components/App.js#L55

**Comment by luckyluck** [comment]
To be honest, I introduced context to see how it suits an app. IMHO, it's pretty good and we need less code to start using it. Also, there is an Ant provider which uses React Context API and take responsibility to spread all given data down to children components. We can use it and replace all Consumer instances with props values. All in all, I would prefer to go with Context API, especially, keeping in mind React Hooks which is coming soon. 

Could you please share your opinion about that? What should we keep and what remove?

**Comment by luckyluck** [comment]
Got rid of Redux in _improvements_ branch.
