### ISSUE TITLE
sync history

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#121]
hard to find any data in the demo site, but this is the format:

```
// https://registry-demo.gbif-dev.org/installation/1234b3aa-f762-11e1-a439-00145eb45e9a/metasync?limit=50
{
  "offset": 0,
  "limit": 50,
  "endOfRecords": true,
  "count": 3,
  "results": [
    {
      "installationKey": "1234b3aa-f762-11e1-a439-00145eb45e9a",
      "syncDate": "2016-01-28T15:35:35.508+0000",
      "result": "IO_EXCEPTION",
      "details": "Synchronization failed with error [java.net.ConnectException: Connection refused]. 0 datasets were updated. 0 datasets were added. 0 datasets were deleted."
    },
    ... 
  ]
}
```

it is simply a list of how the synchronizations went. Just a log really.

**Comment by MortenHofft** [comment]
crawl history example: http://api.gbif-uat.org/v1/dataset/2100a30a-310b-4bf6-ae48-3b06fe881eda/process - but let us wait with that for now. We can do that as part of the management tools.
An example of how it shows there: https://management-tools.gbif-uat.org/crawl-history?uuid=933a9d40-b04a-4223-a97e-bc9a80e2490d

**Comment by luckyluck** [comment]
@MortenHofft, would you mind to close an issue if there is no need to work with it now? Just to clear the list of issues to work with.

**Comment by MortenHofft** [comment]
Please just close issues that you have implemented - it is often hard for me to tell. If you are in doubt, I'll gladly help test it. Other than that I trust that you to close issues. I understand that to mean this is completed then?
