### ISSUE TITLE
feedback when creating new items

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#123]
currently we simply redirect to the created item. Which makes sense. But some reward feedback would be nice and could cary information that might be useful. For example informing the user, that it can take 10 minutes for the dataset to show on the website and that it needs to be crawled to be updated and that that can take hours.

Could be as simple as a little transient message between breadcrumb and data card.

Example of success feedback https://preview.pro.ant.design/result/success

**Comment by luckyluck** [comment]
Implemented enhancement can be checked here https://enhancement--gbif-registry-demo.netlify.com/.
As an example, you can see the screenshot below.

![50aac2fbed](https://user-images.githubusercontent.com/2361566/52943078-84f0df00-3396-11e9-8733-2b4712a33ae6.png)
