### ISSUE TITLE
ui contextual information

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#13]
Since all pages look largely the same (the search interfaces all look alike and so does the content types) it might be nice to add some context clues.

e.g. above the "paper":
A bread crumb on larger devices.
A type:title

I believe there is such an example in the original document, though I find it visually a bit weird. But a variant of it would perhaps increase usability?

**Comment by luckyluck** [comment]
Yes, I agree with you. I thought about crumbs before. 
Which structure would be better to use? For example, **Organizations/ORGANIZATION_TITLE/Contacts/CONTACT_NAME** or something else?

**Comment by MortenHofft** [comment]
Looks good to me

Organizations/Search
Organizations/Search Deleted
Organizations/ORGANIZATION_TITLE
Organizations/ORGANIZATION_TITLE/contact

Organizations/ORGANIZATION_TITLE/Contacts/CONTACT_NAME is in a popup so I wouldn't bother with a breadcrumb for that unless it is also a URL

**Comment by MortenHofft** [comment]
Another proposal for easing navigation

Perhaps instead of writing overview we could write the type of content you are on. So in this case it could say `Organization`. (I can also see this from the menu, but that might be closed on a smaller device.

**Comment by luckyluck** [comment]
I renamed Overview to item type (Organization, Dataset, etc.). Also, I added BreadCrumbs as you proposed, except popup. Is it really something necessary?

**Comment by MortenHofft** [comment]
I don't think you should change breadcrumb on popups no
