### ISSUE TITLE
UI: paging information in header on search

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#14]
the header on search tables currently show the count of results. it would be useful to also see the page you are on `page 1/18`

**Comment by MortenHofft** [comment]
![screen shot 2018-12-14 at 10 39 09](https://user-images.githubusercontent.com/6759267/49995468-849a2900-ff8c-11e8-99bf-1a09ddf51f62.png)

**Comment by luckyluck** [comment]
Added enhancement can be checked here https://enhancement--gbif-registry-demo.netlify.com/organization/search.
