### ISSUE TITLE
impossible to add the right contact

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#165]
What to do in a situation like this. It is always an issue for autocompletes where name isn't unique (same goes for datasets) - but for names it seems more likely to happen.

![screen shot 2019-01-09 at 14 20 15](https://user-images.githubusercontent.com/6759267/50901906-c4342380-1419-11e9-8bc9-2a5b346b0e64.png)

**Comment by luckyluck** [comment]
@MortenHofft, I think that we can add position or email next to the first name. Of course, there are contacts without both parameters, but it looks like an improvement for me.

**Comment by MortenHofft** [comment]
I believe email was included in the suggest for that very reason. Yes please add the email if there

**Comment by luckyluck** [comment]
@MortenHofft, I added an email next to the first name. But in the case that you demonstrated on the screenshot above no one has an email or position.

**Comment by MortenHofft** [comment]
in that case the uuid pasting solves it
