### ISSUE TITLE
site crashes on certain installation pages

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#171]
https://gbif-registry-demo.netlify.com/installation/7857582d-033e-4c54-92e1-330638596cef

the new renderActionMenu is apparently bugged.

**Comment by MortenHofft** [comment]
Apparently it will fail on all pages that has a drop down menu. I don't believe the implementation of the dropdown has been completed?

**Comment by luckyluck** [comment]
I forgot to copy-paste render menu method.
