### ISSUE TITLE
Make search page with filters instead of multiple search pages per type

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#176]
Currently we have 5 dataset lists in the menu. The menu is getting quite large already and more is coming (management tools and vocabulary). For the most part I suspect the user just want to search all active datasets. The option to see `deleted/noEndpoint/duplicates/constituents` could the be considered filters (toggle in case of deleted). In the case we would have one search page for datasets, with filters for when you need to search for duplicates.

**Requirement**: To do so nicely we would need them all to be searchable `q=something`. This is not supported by the API at this point.

Same story for organizations,installations etc.

![screen shot 2019-01-14 at 10 32 24](https://user-images.githubusercontent.com/6759267/51104900-bb5f9b00-17e7-11e9-9164-2d83d500a6af.png)

**Comment by luckyluck** [comment]
Enhancement can be checked here https://enhancement--gbif-registry-demo.netlify.com/.

**Comment by MortenHofft** [comment]
Looks good too me. One small bug though. If I enter a search string and then change view to sat deleted, then the search string remains and the text will say: `12 results for "test string"` which is wrong as the results aren't filtered by that string.
