### ISSUE TITLE
user denmark can not edit datasets from endorsed orgs

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#178]

**Comment by luckyluck** [comment]
@MortenHofft, could you please clarify the bug? Would you mind to provide and example?

**Comment by MortenHofft** [comment]
Login as user denmark
go to one of the organizations endorsed by the node (that `denmark`has in scope) and from there to one of those datasets. Those should be edditable by the user. But they are not.
ex:
https://gbif-registry-demo.netlify.com/dataset/84c6cb56-f762-11e1-a439-00145eb45e9a
