### ISSUE TITLE
suggest using uuid

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#182]
I think it be useful to be able to paste uuids into suggests and get the resolved value. This is especially so the case for persons where the same name might appear many times in the suggest.

**Comment by MortenHofft** [comment]
I don't see why this should be a feature specific to persons - it is useful in general I would think?

**Comment by luckyluck** [comment]
@MortenHofft, could you please clarify what did you mean? Perhaps, you meant search by UUID?

**Comment by MortenHofft** [comment]
yes. search by uuid seems relevant for all the suggests
