### ISSUE TITLE
suggests more self contained

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#183]
Have you considered making the suggests more self contained?

Currently the logic for organization suggest is replicated in both installation and dataset for example (at least it seems to be).

Also the consumer of the suggest need to know the resolved title of the uuid to initialize it correctly. I'm thinking that it might be a more usable component if it handled those things.

Just a thought.

**Comment by luckyluck** [comment]
@MortenHofft, I moved common logic to a separate component SuggestedOrganizations and added logic to search by UUID if user pass value in a valid format. If it's enough for this issue, would you mind to close it?
