### ISSUE TITLE
Node contacts information

### ISSUE THREAD

**Issue by jlegind** [gbif/registry-console#195]
The node contact people do not show up in the new registry.
https://gbif-registry-demo.netlify.com/node/cdc9736d-5ff7-4ece-9959-3c744360cdb3/contact 

I would like to see this information along with email addresses for the node staff.

**Comment by MortenHofft** [comment]
I don't see any in the APIs. I suspect that is the reason
https://registry-demo.gbif-dev.org/node
same goes for the existing registry
https://registry-demo.gbif-dev.org/web/#/node/cdc9736d-5ff7-4ece-9959-3c744360cdb3/contact

**Comment by MortenHofft** [comment]
it works. there just isn't any data in the API. I just confirmed with the dev-api
https://registry.gbif-dev.org/node/03e816b3-8f58-49ae-bc12-4e18b358d6d9
