### ISSUE TITLE
render props for context vs HOC

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#20]
https://github.com/gbif/registry-console/blob/b7ccc54f6f159924904ec3a9386cd058de1a72c2/src/components/common/ContactList/ContactCreateForm.js#L49

this is a preference thing - but could you consider moving the context to a HOC instead? I find render props verbose for the most part and the form is big as it is. And we even need to do it twice in the form for both enums. Same goes for the oranization form.

See also https://github.com/gbif/registry-console/issues/12 for discussion on overall approach

**Comment by luckyluck** [comment]
I added a HOC for that to wrap the whole component instead of each piece of form. I'll try to figure out how to get rid of Redux.
