### ISSUE TITLE
Automatic logout after inactivity

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry-console#205]
I'm not sure where is the best place to implement this (ui or backend) but given the administrative power of this console (e.g. ability to trigger huge deletions in GBIF.org) I suggest we enforce automatic logout after e.g. 30 mins of inactivity.

I foresee an administrator at some point accidentally leaving a computer logged in somewhere or e.g. a stolen is laptop etc.

**Comment by MortenHofft** [comment]
Okay. The most secure would then be that the API only issued tokens that lived for 30 min.
If we use the login for other systems then the login will also expire after 30 min, but I guess that is then desirable as the same token can be used to delete etc.

The portal and col will not be affected by this currently as they issue their own tokens.

**Comment by MortenHofft** [comment]
As an additional step we can also use session storage only. Currently there is an option to keep me logged in after I close the browser. The token lives for a week I believe.

**Comment by MortenHofft** [comment]
> I suggest we enforce automatic logout after e.g. 30 mins of inactivity.

I believe that was the original implementation by @asturcon until I convinced him to let them last for a week

**Comment by asturcon** [comment]
@MortenHofft should I change the expiry time?

**Comment by MortenHofft** [comment]
I can also do it in the browser, but of course it would be more secure if you did so. It wouldn't be the expire time only. It would also be renewing it if it is used within those 30 min. And if so, then the client would need to know that it had been renewed i guess. Else the client believes the token has expired and will remove it (at leat in the current implementation)

**Comment by asturcon** [comment]
At first, I implemented it that way. I was creating a new token each time I receive a valid token (you can't modify a existing one) and returned the new token in a header in the response. Would that be ok for the client?

**Comment by MortenHofft** [comment]
i would think so. @luckyluck there is already a wrapper in Axios that preprocess responses aren't there? We could update the token there perhaps?

**Comment by MortenHofft** [comment]
It looks reasonable to me @asturcon - it should be doable and a simple change as well.

**Comment by asturcon** [comment]
Deployed in DEV and DEMO. The header in the response is called "token".
