### ISSUE TITLE
Implement default values for datasets

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry-console#206]
On a dataset page, we would like to be able to add default values. An example follows showing 2 default values given:

```
individualCount = 1
kingdom = Plantae
```

These are then used in processing, so that any record in the data where the value is NULL is replaced with the default value.

Default values are themselves stored as machine tags. However, machine tags is rather unintuitive for a user. I propose that we introduce a new "Default values" option in the sub menu for dataset and present them nicely, but underneath simply create machine tags. 

A machine tag JSON for a default value is shown (they go in the `default-term.gbif.org` namespace):

```
{
  "key": 149698,
  "namespace": "default-term.gbif.org",
  "name": "individualCount",
  "value": "1",
  "createdBy": "MattBlissett",
  "created": "2018-10-05T14:55:30.731+0000"
}
```

The name and the value are Strings.

I'd recommend placing this after "Contacts" in the dataset sub menu (i.e. with high prominence)

**Comment by MortenHofft** [comment]
@luckyluck just to clarify

new menu item (really just a different styling and showing a subset of machine tags (those with namespace `default-term.gbif.org`)

![screen shot 2019-02-06 at 10 05 51](https://user-images.githubusercontent.com/6759267/52330902-f2942700-29f6-11e9-97ec-fda2d1fbdbc9.png)
When creating a new, it is really just creating a new machine tag with namespace `default-term.gbif.org`.

![screen shot 2019-02-06 at 10 01 46](https://user-images.githubusercontent.com/6759267/52330905-f58f1780-29f6-11e9-8a57-4afcda1116b0.png)

I'm okay with leaving machine tags as is: meaning showing all values (including those with namespace `default-term.gbif.org`.

**Comment by luckyluck** [comment]
@MortenHofft, I implemented default values and you can check how it works [here](https://enhancement--gbif-registry-demo.netlify.com/dataset/b8d715b8-0e65-4b78-a882-d617e934c8a3) (this is a dataset with both, machine tag and default value). The only one difference from your explanation that I see is that I added a filter to separate items on pages. But I can remove this filter and show on Machine Tags page all items.
