### ISSUE TITLE
Translating error messages

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#21]
https://github.com/gbif/registry-console/blob/b7ccc54f6f159924904ec3a9386cd058de1a72c2/src/components/Organization/index.js#L78

I'm good with having hardcoded error messages during development. But it might be worth making a note TODO that this have to be taken from the translation file at some point. Just so we remember and can find the places that needs updating

**Comment by luckyluck** [comment]
I removed this method and wrapper in general and replaced all that with error dispatcher. Anyway, I'll figure out how to replace that with Context. 
Still, I have a question about request error catching. As for me, it doesn't look handy to add catch part to every API request in all components and add Redux (or Context). What do you think about that? Probably, it'd be better to add catch statements within API or API "facade" or wrapper? Could you please share your opinion?

**Comment by MortenHofft** [comment]
But the component is likely to know about the error anyhow to show an in-page error. At least I find that having error messages centralised has often led me to refactor to give more specific error messages and to avoid having more than one summarised error. 

Currently looking at a 404 organisation e.g. only shows a root error, but it should probably show a page specific error instead. Currently it just shows an infinite spinner. A page 404 would be more appropriate and informative. I *think* that I prefer error handling on this level to be handled by the caller who knows how critical it is and knows what it means for the user and how it should be displayed.

**Comment by luckyluck** [comment]
Added error handlers to requests of list pages, requests to get/update item, get/update/delete subtype. All errors will be shown to the user via the Notification component.

**Comment by MortenHofft** [comment]
Sounds to me like this issue can be closed - if not feel free to reopen
