### ISSUE TITLE
more details on dataset ingestion history

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#220]
https://management-tools.gbif.org/crawl-history?uuid=e6fab7b3-c733-40b9-8df3-2a03e49532c1
vs
https://registry.gbif.org/dataset/e6fab7b3-c733-40b9-8df3-2a03e49532c1/process

The old version had more details. I wonder if we should add this extra info to the new one as well?

![screen shot 2019-02-01 at 14 33 45](https://user-images.githubusercontent.com/6759267/52126034-81d3c000-262e-11e9-88ff-44fc50fa9f78.png)

**Comment by luckyluck** [comment]
@MortenHofft, I added more columns, can be checked in bug-fix branch. Would you mind to check if you have time?

**Comment by MortenHofft** [comment]
perfect. thank you. i haven't checked that the numbers are correct, but trust it is the same numbers/fields as in the existing 👍

**Comment by MortenHofft** [comment]
Ahh - the out of sync info. That is actually useful. Could you please add it next to the headline `Ingestion history`

**Comment by luckyluck** [comment]
@MortenHofft, to save implementation of ProcessHistory component as it is I added info under the headline as it was in the management tools. But, if there is a strict requirement, I will change implementation for ProcessHistory component.

**Comment by MortenHofft** [comment]
@luckyluck I'm not sure I understand. Could you please refer to a link or post a screenshot? I've looked at the branch where above commit was made, but do not see anything there.

**Comment by luckyluck** [comment]
Also, here is an example https://bug-fix--gbif-registry-demo.netlify.com/dataset/29886bf9-62d2-4208-87f6-109dd1972607/process that I found on DEV server, but without Out of Sync items.

**Comment by luckyluck** [comment]
And here is an example with Out of Sync label https://bug-fix--gbif-registry-demo.netlify.com/dataset/5152f65f-ec13-4847-a02e-3cb454ae6dd5/process
