### ISSUE TITLE
rename GrBio to GrSciColl

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#223]
it has been decided, that the name for these entities should be grscicoll instead and we should change it throughout. The API has changed in demo and dev. The registry code should be updated to match the new endpoints and the entities should be renamed where we call it by its old name `grbio`

**Comment by luckyluck** [comment]
@MortenHofft, sorry, do you mean to replace all GRBIO strings in translation files with GrSciColl? For example, View on GRBIO, GRBIO staff, etc?

**Comment by MortenHofft** [comment]
Not only that: the API endpoints have changed as well (hence [it doesn't work now](https://gbif-registry-demo.netlify.com/collection/search)) and it would be nice if the variable naming etc matched as well. Just because the next person looking at the code will wonder why everything is called "grbio" when that name appear nowhere else.
