### ISSUE TITLE
Document how to add a new language

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#226]
@luckyluck What to do if a new language should be added? Please create a seperate .md file describing this process.

**Comment by luckyluck** [comment]
I created an instruction "How to add a new language" with additional information about localization of the App. Instruction can be found [here](https://github.com/gbif/registry-console/blob/rtl/LANGUAGES.md).
Additionally, I allowed myself to change a bit the way how we manage localization and refactored [translations.js](https://github.com/gbif/registry-console/blob/rtl/scripts/translations.js) script.  

P.S. Accidentally, I linked changes to the #88 issue.
