### ISSUE TITLE
created timestamp vs "xxx days ago"

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/registry-console#233]
User downloads are shown in 3 columns, e.g. 

https://registry.gbif.org/user/dnoesgaard/download

Name | Status | Created
-- | -- | --
{"type":"or","predicates":[{"type":"equals","key":"OCCURRENCE_ID","value":"urn:catalog:O:L:18835"},{"type":"equals","key":"OCCURRENCE_ID","value":"LD:General:1562300"}]} | SUCCEEDED | 7 days ago

The value used in Created (xx ago) is really not helpful, as I'm often looking for a specific date, not the period since the download. Can't we change this to the `created` date?

**Comment by MortenHofft** [comment]
The behaviour is modelled after the old registry assuming that was a deliberate choice. But both @MattBlissett and @dnoesgaard have asked for tables to show absolute dates instead. @luckyluck 
 I suggest changing it for all tables and see if anyone complains about the changed format.

See also https://github.com/gbif/registry-console/issues/200
