### ISSUE TITLE
Fiji phone numbers won't validate

### ISSUE THREAD

**Issue by jlegind** [gbif/registry-console#238]
I tried updating the tile on the Fiji publisher The University of the South Pacific 
https://registry.gbif.org/organization/d3ed306d-f994-4fb0-abeb-a9a373e20728

But the existing phone number for the institution would not pass validation, so I had to remove it.
+679 323 2930

The dialling format changed in 2002 from six to seven digits https://en.wikipedia.org/wiki/Telephone_numbers_in_Fiji

**Comment by MortenHofft** [comment]
I'll look to see what validation the frontend does, but probably shouldn't do more than testing than expecting plus + space/digits testing + space and numbers a la /^(\+)?[0-9\s]+$/
