### ISSUE TITLE
login cookie?

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/registry-console#239]
I've noticed that I have to re-login every time I access the console–even if simply opening a link in a new tab. Is there no session cookie for the login?

**Comment by luckyluck** [comment]
I replaced sessionStorage with the cookie because the browser doesn't share sessionStorage between tabs. Here [changes](https://multitubs--gbif-registry-demo.netlify.com/) can be checked.

**Comment by dnoesgaard** [comment]
Much better :)
