### ISSUE TITLE
Create and maintain network entries and network memberships

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/registry-console#240]
A "network" in the GBIF data context is a grouping of individual datasets across different publishing institutions to a thematic or taxonomic theme, where not all datasets of a given publisher necessarily qualify. Examples from the past were HerpNet (Herpetology) or ORNIS (birds); at present, we have one such network: OBIS, with the network page at https://www.gbif.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6 (so far, available as a link from the dataset page). 

There are more such networks to come, like the Freshwater Network, so that the registry interface should eventually allow to
- create/update/delete entries in the 'network' table, with appropriate warnings and safeguards for deletion / data integrity
- associate existing datasets with networks (table dataset_network)
- remove specific entries from the dataset_network table

**Comment by luckyluck** [comment]
@MortenHofft, I was trying to add a new constituent dataset to the network using the documented route for that
`https://registry-demo.gbif-dev.org/network/5e67af89-cf0f-4972-95af-b4d48d91e9c8/constituents POST`
and found that this type of request is not allowed on the demo server (HEAD, GET, OPTIONS types are allowed due to response). 
Could you please tell if it's my mistake or the API on the demo should be updated?

**Comment by MortenHofft** [comment]
@asturcon you can answer this better than I

**Comment by asturcon** [comment]
It looks like the dataset key has to be in the URL. Hence, the request should have this form: 

network/{key}/constituents/{datasetKey}

I think the documentation for this method is wrong, or not accurate at least.

@luckyluck can you please try with that? Unfortunately I'm not at the office these days so I can't test it 😢

**Comment by luckyluck** [comment]
> It looks like the dataset key has to be in the URL. Hence, the request should have this form:
> 
> network/{key}/constituents/{datasetKey}
> 
> I think the documentation for this method is wrong, or not accurate at least.
> 
> @luckyluck can you please try with that? Unfortunately I'm not at the office these days so I can't test it 😢

Yes, REST with datasetKey works, thank you.
