### ISSUE TITLE
allow admins to add user scopes

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#244]
See https://github.com/gbif/registry/issues for API

Registry admins should be able to add editor scopes to a user.

**Comment by luckyluck** [comment]
@MortenHofft, I checked this task. Changes could be checked [here](https://user-scopes--gbif-registry-demo.netlify.com/).

**Comment by MortenHofft** [comment]
Looks good - but the link of the associated org or node opens in a new tab. Elsewhere we use the same tab for links. Any reasons to open this in a new one?

**Comment by luckyluck** [comment]
Yes, you are right. I'll fix it soon.
