### ISSUE TITLE
UK phone number wont validate

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/registry-console#246]
A UK phone number in the form +44 1111 111111 wont validate

**Comment by MortenHofft** [comment]
Same as in https://github.com/gbif/registry-console/issues/238
My preference is still to drop that phone number validation library as suggested in https://github.com/gbif/registry-console/issues/238#issuecomment-467825205

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/registry-console/commit/e463c660a2eee7201ca18d6659ff5c27a3db7579
