### ISSUE TITLE
why do we run tests in serial? --runInBand

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#248]
@luckyluck I wonder why we have introduced a `--runInBand` flag on tests? Is it a mistake (from debugging) or a deliberate choice?

**Comment by luckyluck** [comment]
@MortenHofft, Initially, it was a way to fix an issue with production build - this option turns off Jest cache as one of the effects.
But recently several updates of React and react-scripts were released and we can try to update dependencies and get rid of this option in a separate branch. If you approve this, I'll do it in a moment.

**Comment by MortenHofft** [comment]
Sound good to try to update either way. yes please.
