### ISSUE TITLE
Phone numbers and postcode invalid when containing "-"

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#249]
The problem is that they are accepted in the registration form on GBIF.org but not on the registry. This means that if I try to update something unrelated on an organisation page, I can't save it because the post code isn't accepted.
See an example [here](https://registry.gbif.org/organization/cae7b6c7-669a-4261-9a34-6e8cdc16a1250).

**Comment by MortenHofft** [comment]
That example do not work for me - it is a 404
The console is overly strict given how much data we have that do not adhere to those validations. It is tricky, we want new data to be good, but we also have to support legacy data. Until the backend starts to enforce a check, I will remove it in the client as well.

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/registry-console/commit/1023c281c3dabea92a27813f2059c08dec3a5083
