### ISSUE TITLE
Run from a local API

### ISSUE THREAD

**Issue by MattBlissett** [gbif/registry-console#251]
I'm creating an example Ansible+Vagrant setup so anyone can run the Registry webservice. It's useful if they can also use the console.

https://github.com/gbif/registry-console/blob/master/src/api/util/config.js#L44 defaults to the Demo API, but I'd like to use localhost.  Will that disrupt your development of the console?

If so, maybe we can use an environment variable to override the guessed configuration.

See also https://github.com/gbif/registry/issues/105

**Comment by MortenHofft** [comment]
@luckyluck could you please check if CRA have a standard way of defining/using environment variables?

**Comment by luckyluck** [comment]
Yes, there is an official way to use variables. A detailed explanation can be found [here](https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables). As an example, I added several variables for demo configuration and pushed changes to the separate branch.

**Comment by luckyluck** [comment]
And here is my local .env.local file:
`
REACT_APP_URL=https://www.gbif-dev.org
REACT_APP_API=https://registry-demo.gbif-dev.org
REACT_APP_API_V1=//api.gbif.org/v1
`
