### ISSUE TITLE
Postal code must be optional

### ISSUE THREAD

**Issue by MattBlissett** [gbif/registry-console#252]
Many countries don't have post codes, many current entries have a NULL post code.

Noticed on the organization form.

**Comment by MortenHofft** [comment]
@luckyluck I broke that when i changed the postal code validation. I now notice that the validators in helpers are also where it is defined if it is required at all. Wouldn't it make sense to separate that? It makes sense to have telephone required one place, but not another. But using the same validator if there are any text.

**Comment by luckyluck** [comment]
@MattBlissett, I checked all forms that Registry Console has and noticed that all Postal Code fields are optional. Should we remove the field or do something else?

**Comment by MortenHofft** [comment]
Keep the field, but make it optional please.

**Comment by luckyluck** [comment]
@MortenHofft, I removed validator. I'll create a new pull-request when Travis finishes branch build.
