### ISSUE TITLE
Editing institution record --> network error

### ISSUE THREAD

**Issue by kcopas** [gbif/registry-console#255]
Just trying to update the ZMUC record, but I can't save my changes. Error message says "Error: Network error", so not much to go on there.

**Comment by kcopas** [comment]
Tried again, this time it worked (including adding a specimen number of 10,000,000!).

Sorry about not including a link—I went back to copy it, got distracted and hit submit on the issue.

https://registry.gbif.org/institution/68fcaba0-61fe-4e78-a460-4f37654d025d

Noting for myself that this obviously this doesn't publish immediately to GBIF.org:
https://www.gbif.org/grscicoll/institution/68fcaba0-61fe-4e78-a460-4f37654d025d

Will there be a publishing routine for such updates, or am I just overindulged with instant gratification?

**Comment by MortenHofft** [comment]
Species number still shows as 9999, because I haven't deployed to production. Sorry. But good thing that it could update. In that case it probably was an outage.

It should show the updated version - though there could be 10 minutes cache delay. But I don't see the number either.

**Comment by MortenHofft** [comment]
The data seem to be just fine in the API
https://api.gbif.org/v1/grscicoll/institution/68fcaba0-61fe-4e78-a460-4f37654d025d

we just don't show that number on the institution page. Seems reasonable to do.
