### ISSUE TITLE
Running ingestions view needs to be more compact

### ISSUE THREAD

**Issue by MattBlissett** [gbif/registry-console#256]
The old one has little padding on the table rows, so we can fit more rows to have an overview of more running ingestions.

Old one: https://management-tools.gbif.org/crawling-monitor

I'd like to fit around 20, similar to the old one.

**Comment by luckyluck** [comment]
@MattBlissett, I set the same paddings for table cells as it was in the old interface. Changes can be checked [here](https://ingestions--gbif-registry-demo.netlify.com/monitoring/ingestion).
