### ISSUE TITLE
Running ingestions doesn't show current counts

### ISSUE THREAD

**Issue by MattBlissett** [gbif/registry-console#257]
The occurrence count:

>  Consortium of California Herbaria (2,320,628 occ)

is very useful, could this be added?

It should exist for datasets of type OCCURRENCE, CHECKLIST and SAMPLING_EVENT, but it doesn't matter if (like on the old one) its visible for all datasets.

For datasets of type CHECKLIST (or all datasets), it would also be useful to have a count of the number of name records: https://api.gbif.org/v1/species/search?dataset_key=7ddf754f-d193-4cc9-b351-99906754a03b&limit=0

Ideally these belong in two extra columns (EO existing occurrences, EN existing names? Before ST) so they can be used in sorting. I think they were just kludged in for the old one.

**Comment by luckyluck** [comment]
@MattBlissett, I added counts with the same stales as they were in the old interface. It can be checked [here](https://ingestions--gbif-registry-demo.netlify.com/monitoring/ingestion).
