### ISSUE TITLE
when i add a new dataset to a network it doesn't show in the list

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#262]
when i add a new dataset to a network it doesn't show in the list
But it does tell me that it was successfully added

**Comment by MortenHofft** [comment]
looks like missing cache control

**Comment by luckyluck** [comment]
@MortenHofft, I checked it locally and on the [test server ](https://network--gbif-registry-demo.netlify.com/) - demo API returns header 
`cache-control: no-cache, no-store, must-revalidate
`
and re-requested list returns a new number of datasets. The only bug that I found is that the counter in the menu does not update itself. I'll fix it.

**Comment by MortenHofft** [comment]
Thanks. The API has been fixes since
