### ISSUE TITLE
networks gives uninformative error when adding an existing dataset

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#263]
the API simply returns an error 500 when I try to add an existing dataset.
@asturcon I suggest something more informative for this. I'm not sure what code, but 500 doesn't seem ideal?

**Comment by asturcon** [comment]
It could be a 422 Unprocessable Entity. Anyway we have to decide if we should do it now or wait till we rewrite the registry since this behaviour is common for all the entities and it has to be consistent. @fmendezh

**Comment by MortenHofft** [comment]
it actually does return a message with a long dump. but it does actually state the reason. I'm closing the issue
```
### Error updating database. Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "dataset_network_pkey" Detail: Key (dataset_key, network_key)=(39f36f10-559b-427f-8c86-2d28afff68ca, b153643d-735a-440f-a0e9-428b4f9d1cd2) already exists. ### The error may exist in org/gbif/registry/persistence/mapper/NetworkMapper.xml ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### SQL: INSERT INTO dataset_network(dataset_key,network_key) VALUES( ?, ? ) ### Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "dataset_network_pkey" 
...
```
