### ISSUE TITLE
networks: add networks as a tab to the dataset as well

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#264]
now that we got networks, it makes sense to also add those to the dataset.

to get networks from a dataset: https://registry-demo.gbif-dev.org/dataset/6995b180-5755-499d-bf3e-1c8d83b42ac3/networks

@ahahn-gbif could you please clarify. what is the expected workflow around this? Who will manage this? Your team only or do we expect dataset owners to do that association? Or the networks? I'm asking because if it is datasets/organisations and nodes that are to do so, then we need to be able to add networks from the dataset page as well (currently it is only from the network page that you can add a dataset) - or at least that makes authentication easier.

**Comment by timrobertson100** [comment]
For the propose of the registry-console we aim for:

1. If you are eligible to edit a dataset you should be able to associate it with any network
2. Only registry admins create and modify the networks from the network menu item

However the API for networks is restricted to registry_admin today so suggest limit the UI for both to only admin role

**Comment by MortenHofft** [comment]
@luckyluck could you please add the network tab to datasets and an option to add a network to the dataset (from dataset/uuid/network) if logged in as ADMIN, but make sure that the role can be extended to anyone with the dataset in scope once that feature has been implemented in the backend.
