### ISSUE TITLE
authentication issue

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#265]
hard to reproduce bug report :(
despite just having logged in as ADMIN i got a 401 rejection on an organisation page. I managed to reproduce it twice. Then not again. Not exactly a clear bug report, but something seemed fishy. It might have been me, but I'm fairly certain it wasn't.

**Comment by MortenHofft** [comment]
I notice that demo environment still have cache headers `cache-control: public, max-age=3601` - might be related?

**Comment by MortenHofft** [comment]
I'm closing this as I assume it has to do with faulty cache control in demo environment

**Comment by asturcon** [comment]
@MortenHofft cache in demo should be fixed now. Next week I'll make this workaround permanent
