### ISSUE TITLE
validation on chips in forms

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#27]
could we have validation on chip fields. email e.g. isn't validated I see.

![screen shot 2018-12-14 at 12 33 52](https://user-images.githubusercontent.com/6759267/50001263-a1d6f380-ff9c-11e8-80d1-e27d538eeaf7.png)

**Comment by luckyluck** [comment]
I added a wrapper for forms with several custom validation handlers. Could you please check a list of required fields on the "Create new Contact" form.
