### ISSUE TITLE
Clearer error message when user doesn't have permissions

### ISSUE THREAD

**Issue by asturcon** [gbif/registry-console#274]
When a user is not allowed to do an action because of lack of permissions the message shown is "An error occurred". It'd be nicer to say that the user is not allowed to do that action or something like that.

**Comment by MortenHofft** [comment]
Agreed. And the user shouldn't see the action at all if possible to detect this up front. Can you give provide the context/action where you see this please

**Comment by asturcon** [comment]
With the new roles added for grscicoll you can see it with any user when you try to do something with collections (DEV and DEMO for now, rest of envs soon)

**Comment by MortenHofft** [comment]
It makes sense that adding new permission rules might have consequences for the front end (such as not showing buttons that you aren't allowed to use).

But if you see this, then it must be because registry admins no longer have access to edit grscicoll?
