### ISSUE TITLE
UI: tables on mobile

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#28]
The current tables do not work on mobile.
I only know of two ways I like.

1) rearrange rows to cards with key:value pairs
2) make the table horizontally scrollable (the table only, not the whole page of course)

I'm good with either in this case - the easiest is probably to go with the scroll option.

Other suggestions are welcomed as well.

**Comment by luckyluck** [comment]
I decided to go with the table right now. But I'd prefer to add cards for mobiles later when I finish core features.
