### ISSUE TITLE
Specify under which condition datasets metadata will be overwritten

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#288]
I'm not sure when datasets will be overwritten. Could someone qualified please do so?
@MattBlissett you are my best guess for someone able to do so.

https://github.com/gbif/registry-console/blob/c4c9fe6ec46c08f438cb70a2d4b29d0d003291ce/locales/en.json#L1445

**Comment by MattBlissett** [comment]
How about this:

> The primary source for this information is the published metadata: EML files (separate or contained within a Darwin Core Archive) or BioCASe collection metadata. Wherever possible, the data provider should change the metadata at source, such as in an IPT or in BioCASe. 
>
> Changes in the data publisher's metadata will overwrite manual changes made here. To prevent this, select "Lock auto updates".
>
> The most common reason to edit the information here is ① the dataset is offline, ② the dataset is a duplicate to be deleted, ③ the publisher is unable to update their published metadata in a reasonable time.

@gbif/content, is this helpful?

**Comment by ahahn-gbif** [comment]
Thanks Matt, that summarizes it nicely. It is really already contained, but to avoid future frustration, it needs to be clear that once the "Lock auto updates" is set, any possible future changes of the metadata at source, e.g. when curation resumes, will be ignored until the lock is explicitly lifted in the registry. When it is, then the locally served metadata will again have precedence over any manual edits done in the registry:  there is no automatic consolidation of the two versions, no preservation of the manually edited version, and no warning that it will be replaced. This in mind, the "lock auto updates" should only be used in cases where it is absolutely necessary to centrally edit a dataset entry, and where it is unlikely that it will be rolled back again. The primary source should, by default, be the locally maintained resource metadata, from which the registry synchronizes any updates.

**Comment by MortenHofft** [comment]
I have added @MattBlissett's changes. If it is not clear enough please reopen with a suggestion for a more accurate text. If the tooltip popup isn't sufficient to explain it, then let me know and we add an article tab or similar to explain it in full details
