### ISSUE TITLE
Cannot click endorsement for Participant Node Managers Committee because content invalid

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#290]
The URL for the logo of https://registry.gbif.org/organization/84e9f3f5-0683-41a4-a480-e80714d5e7c2 is invalid.
The problem is that I can't endorse them on behalf of the Participant Node Managers Committee because the registry doesn't validate the content. The only solution I have is to remove their logo.

Edit: I did remove the URL link, but it would be nice if what was accepted in the registration form matched what is accepted by the registry.

**Comment by luckyluck** [comment]
@MortenHofft, as far as I can see, there are 2 ways to solve a problem: to extend logo URL validation rules or to remove validation as we did for postcodes. We can for sure go with the second option. 
By the way, Dataset and Institution forms have the same logo URL validation and users could potentially face the same issue.

**Comment by MortenHofft** [comment]
@ManonGros Was it an invalid url? In that case I think it is fair to say it should be removed (and possibly say that the registry API should validate it when entering data). 
It is a shame that the registry API do not notice it an invalid, but then this is a chance to clean the data before endorsing them...?

**Comment by ManonGros** [comment]
Yes it was an invalid URL (to an image on google drive) and I removed it. But it would be great if the data was checked before it entered the registry.

**Comment by MortenHofft** [comment]
@ManonGros 
> Yes it was an invalid URL (to an image on google drive) 
So the URL is valid right? But the content was not valid? I'm confused

**Comment by MortenHofft** [comment]
Ahh I see the problem. The validator for the registry-console is wrong. It requires it to end with jpg, png etc. Image do not have to do so - it can still be a valid image.

**Comment by MortenHofft** [comment]
thank you @luckyluck - I have removed it from everywhere. We have many images that do not end with a nice .jpg or such :) I think the best we can do is to check that it is a valid URL and if we were to be very through test that it resolves. When entering through GBIF.org we show the logo and an error if it does not resolve to an image. Since that is the primary source for entering organisation data it should catch most errors.
