### ISSUE TITLE
GRBio: linking collection to institution

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#294]
If I try entering something in the `Institution` field on a collection page, I get a blank page.

**Comment by ManonGros** [comment]
The same problem arises when linking anything to anything (users to institutions for example).

**Comment by MortenHofft** [comment]
> The same problem arises when linking anything to anything (users to institutions for example).

Could you please list all of them? I can see why institution select wouldn't work for collection and Staff (and surprisingly never have as far as I can see) and have fixed those.

**Comment by ManonGros** [comment]
Yes sorry I meant when linking staff to institution. But if you have fixed it already this is good now.
