### ISSUE TITLE
Running pipeline ingestions: link to logs

### ISSUE THREAD

**Issue by muttcg** [gbif/registry-console#298]
It would be nice to have a link to the ELK, current template is:

https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:AWBa0XR-f8lu3pmE7ete,interval:auto,query:(query_string:(analyze_wildcard:!t,query:'datasetId:%2282ceb6ba-f762-11e1-a439-00145eb45e9a%22%20AND%20attempt:%2288%22')),sort:!('@timestamp',desc))

Where:
datasetId:%22**82ceb6ba-f762-11e1-a439-00145eb45e9a**%22%20AND%20attempt:%22**88**%22 -> **82ceb6ba-f762-11e1-a439-00145eb45e9a** is datasetKey and **88** is attempt

**Comment by MortenHofft** [comment]
notice that above link do not specify the index.
