### ISSUE TITLE
Timezone in dates

### ISSUE THREAD

**Issue by asturcon** [gbif/registry-console#299]
For example, in the dataset metadata we're showing as timezone UTC + 02:00 but the times returned are in UTC:

![Screen Shot 2019-06-25 at 11 18 01](https://user-images.githubusercontent.com/25691745/60086238-fd97eb80-973a-11e9-932a-9d7130d7b50e.png)

AFAIK in the servers we use UTC time (@MattBlissett can you confirm?)

**Comment by MattBlissett** [comment]
All servers are UTC, `ls -l /etc/localtime` will confirm that.  The database is also UTC, although I think it was Europe/Copenhagen until the migration to new hardware.

I can't immediately explain this issue.

**Comment by MattBlissett** [comment]
prodcrawler1-vh log entry:
```
INFO  [06-28 08:14:27,110+0000] [registry-change-1] org.gbif.occurrence.cli.registry.RegistryChangeListener:  Sending crawl for updated dataset [346a9b13-5c96-4793-bcd7-d6614950e726]
```

API:
```
modified": "2019-06-28T08:13:27.093+0000",
```
Matches.

So this is probably a Javascript problem.
