### ISSUE TITLE
GrSciColl console - user/editor feedback

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#300]
I am forwarding the feedback from one of our editors:
* The search returns persons sorted by their first name and does not display the last name - rather inconvenient.
* Is there any way to associate different roles to staff members? e.g. "Collection manager", "curator", "Project manager", etc. For example, someone can be both the director of an institution and the curator of a collection, is there any way to reflect that somewhere?

**Comment by MortenHofft** [comment]
> The search returns persons sorted by their first name and does not display the last name - rather inconvenient.

All last names are empty, I suspect that is why the developer left the last name out. I can add the empty "last name" column.

>Is there any way to associate different roles to staff members? e.g. "Collection manager", "curator", "Project manager", etc. For example, someone can be both the director of an institution and the curator of a collection, is there any way to reflect that somewhere?

* Only one position is allowed in grscicoll per person apparently. @asturcon I suspect this is per design (modelling the old system)
