### ISSUE TITLE
Wrong encoding on dev for Danish

### ISSUE THREAD

**Issue by muttcg** [gbif/registry-console#311]
Dev registry doesn't display Danish correctly
![Screenshot from 2019-10-10 13-17-50](https://user-images.githubusercontent.com/11806077/66564631-bf470080-eb60-11e9-90e6-4d42560ad7e5.png)

**Comment by MortenHofft** [comment]
just mock data to test that translations work :)

from translation file
```
"country": "[!!Ĉōŭńŧřȳ!!]",
"postalCode": "[!!Ƥōŝťâł čơďē!!]",
```
