### ISSUE TITLE
Not all the fields are displayed on GBIF.org

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#313]
In this example: https://www.gbif.org/grscicoll/collection/2a95140b-f5d7-440c-862b-092958e7d1b2, the content type is available on the registry page but not on the gbif page.
The same goes for the contact information (the address is not visible on GBIF.org).

The same goes for this other example: https://www.gbif.org/grscicoll/institution/40452d31-2f91-460a-a624-7ecf27eac71e where the information available is much richer in the registry (https://registry.gbif.org/institution/40452d31-2f91-460a-a624-7ecf27eac71e).

As editors will make more information available in GrSciColl, it would be great if we were able to use/display it on GBIF.org.

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/0ecde36cbcc1214f989756bbe1800f8071c078b6
