### ISSUE TITLE
cites permit number is a dropdown

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#314]
I notice that institutions have a dropdown with 3 options for citesPermitNumber. That looks wrong to me. @asturcon what is the intended use for this field in the database?

I'm not sure if it was implemented like this in agreement with someone, or it was a best guess (that might well be wrong)

**Comment by asturcon** [comment]
There is no enum for citesPermitNumber so there shouldn't have a dropdown, it's just a String value.

I think someone though the citesPermitNumber was this enum and used it there by mistake: http://api.gbif.org/v1/enumeration/basic/CitesAppendix
