### ISSUE TITLE
filters on pipeline history

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#318]
@asturcon writes

We’ve been doing some changes in the pipelines history and it implies changes in the registry-console UI. I’m still testing it in DEV but if I had the UI adapted to these changes it’d be easier for me to test it.
 
So far we ‘ve had pipeline processes that can have a list of steps. Now, we’ve added a new object in between called pipeline execution to group all the steps that are run together(https://github.com/gbif/gbif-api/blob/pipelineExecution/src/main/java/org/gbif/api/model/pipelines/PipelineExecution.java). So now a pipeline process can have a list of executions and each execution can have a list of steps. Also, a step has now a field with the number of records that were processed in that step. The endpoints are more or less the same (just adding the executionKey to the paths) but the response is a bit different:
 
GET pipelines/history  -> paging supported
GET pipelines/history/{datasetKey}  -> paging supported
GET pipelines/history/{datasetKey}/{attempt}
GET pipelines/history/process/{processKey}/{executionKey}/{stepKey}
 
The endpoints to run or crawl pipelines remain the same.
 
Also, we’ve created a new endpoint https://api.gbif-dev.org/v1/ingestion/history that merges the history of the old system (Solr and so on, I don’t know how to call this system anymore 😊 ) and the pipelines history. We were thinking to merge these 2 tabs in one so we can see all the crawl info and pipelines together:
 

 
You can use this as an example of a response: https://api.gbif-dev.org/v1/ingestion/history/8575f23e-f762-11e1-a439-00145eb45e9a . You can also access to a specific attempt: https://api.gbif-dev.org/v1/ingestion/history/8575f23e-f762-11e1-a439-00145eb45e9a/241
 
 
Finally, for the “Running pipeline ingestions” tab in the monitoring section, we’ve added filters and paging. To do so, there’s a new endpoint http://api.gbif-dev.org/v1/pipelines/process/running/query where you can use the parameters:
datasetTitle
datasetKey
status: it’s a list, you can do status=RUNNING&status=FAILED. This query is an OR. Possible values are RUNNING, COMPLETED and FAILED.
step: it’s a list too. Possible values are http://api.gbif-dev.org/v1/enumeration/basic/StepType (actually the TO_VERBATIM one is not supported)
offset
limit
 
You can combine them as you want. If you add more than one parameter it will be an AND (datasetTitle=pont&status=COMPLETED will find matches only if both conditions are met).
This way, you don’t need to store all dataset titles in the browser to do the searches. The same for pagination. Also, we’d like to be able to filter by all these params in the UI too, maybe adding filters by column.

**Comment by MortenHofft** [comment]
I believe the tables have been updates as per instructed in https://github.com/gbif/registry-console/commit/cf02151d0e0b919a11f098b2e0612635f3b05575

Outstanding: filters on table is still missing.
* [ ] add filters to Running pipeline ingestions tab. You would like multiselect filters for status and step.

**Questions**
Does it make sense to have 2 endpoints  for this ? Is this to be considered equivallent of dataset vs dataset/search? If so should we call it search instead of query?
https://api.gbif-dev.org/v1/pipelines/process/running and
http://api.gbif-dev.org/v1/pipelines/process/running/query

**Comment by MortenHofft** [comment]
It seems confusing to me that we have
https://api.gbif-dev.org/v1/ingestion/history/8575f23e-f762-11e1-a439-00145eb45e9a/241
and
https://api.gbif-dev.org/v1/pipelines/history/8575f23e-f762-11e1-a439-00145eb45e9a/241

with almost the same info, but different field names. Do we need both?

```
{
"key": 10618,
"datasetKey": "8575f23e-f762-11e1-a439-00145eb45e9a",
"datasetTitle": "PonTaurus collection",
"attempt": 241,
"created": "2019-12-09T09:22:32.531033",
"createdBy": "crawler.gbif.org",
"executions": [
{
"key": 3084,
"stepsToRun": [
"TO_VERBATIM"
],
"rerunReason": "ss",
"created": "2019-12-10T16:52:01.060453",
"createdBy": "mlopezg",
"steps": [
{
"key": 11459,
"type": "XML_TO_VERBATIM",
"runner": "STANDALONE",
"started": "2019-12-10T16:52:01.633",
"finished": "2019-12-10T16:52:04.698",
"state": "COMPLETED",
"message": "{\"datasetUuid\":\"8575f23e-f762-11e1-a439-00145eb45e9a\",\"attempt\":241,\"totalRecordCount\":1534,\"reason\":\"NORMAL\",\"pipelineSteps\":[\"HDFS_VIEW\",\"INTERPRETED_TO_INDEX\",\"XML_TO_VERBATIM\",\"VERBATIM_TO_INTERPRETED\"],\"endpointType\":\"BIOCASE\",\"platform\":\"ALL\",\"executionId\":3084}",
"numberRecords": 1534,
"createdBy": "crawler.gbif.org",
"modified": "2019-12-10T16:52:04.700077",
"modifiedBy": "crawler.gbif.org",
"metrics": [
{
"name": "archiveToErCount",
"value": "1534"
}
]
},
```

vs

```
{
"datasetKey": "8575f23e-f762-11e1-a439-00145eb45e9a",
"datasetTitle": "PonTaurus collection",
"attempt": 241,
"crawlInfo": {
"datasetKey": "8575f23e-f762-11e1-a439-00145eb45e9a",
"crawlJob": {
"datasetKey": "8575f23e-f762-11e1-a439-00145eb45e9a",
"endpointType": "BIOCASE",
"targetUrl": "http://ww3.bgbm.org/biocase/pywrapper.cgi?dsa=pontaurus",
"attempt": 241,
"properties": {}
},
"startedCrawling": "2019-12-09T09:21:48.121+0000",
"finishedCrawling": "2019-12-09T09:22:32.060+0000",
"finishReason": "NORMAL",
"processStateOccurrence": "FINISHED",
"processStateChecklist": "EMPTY",
"pagesCrawled": 28,
"pagesFragmentedSuccessful": 28,
"pagesFragmentedError": 0,
"fragmentsEmitted": 1534,
"fragmentsReceived": 1534,
"rawOccurrencesPersistedNew": 1534,
"rawOccurrencesPersistedUpdated": 0,
"rawOccurrencesPersistedUnchanged": 0,
"rawOccurrencesPersistedError": 0,
"fragmentsProcessed": 1534,
"verbatimOccurrencesPersistedSuccessful": 1534,
"verbatimOccurrencesPersistedError": 0,
"interpretedOccurrencesPersistedSuccessful": 1534,
"interpretedOccurrencesPersistedError": 0
},
"pipelineExecutions": [
{
"key": 3084,
"stepsToRun": [
"TO_VERBATIM"
],
"rerunReason": "ss",
"created": "2019-12-10T16:52:01.060453",
"createdBy": "mlopezg",
"steps": [
{
"key": 11459,
"type": "XML_TO_VERBATIM",
"runner": "STANDALONE",
"started": "2019-12-10T16:52:01.633",
"finished": "2019-12-10T16:52:04.698",
"state": "COMPLETED",
"message": "{\"datasetUuid\":\"8575f23e-f762-11e1-a439-00145eb45e9a\",\"attempt\":241,\"totalRecordCount\":1534,\"reason\":\"NORMAL\",\"pipelineSteps\":[\"HDFS_VIEW\",\"INTERPRETED_TO_INDEX\",\"XML_TO_VERBATIM\",\"VERBATIM_TO_INTERPRETED\"],\"endpointType\":\"BIOCASE\",\"platform\":\"ALL\",\"executionId\":3084}",
"numberRecords": 1534,
"createdBy": "crawler.gbif.org",
"modified": "2019-12-10T16:52:04.700077",
"modifiedBy": "crawler.gbif.org",
"metrics": [
{
"name": "archiveToErCount",
"value": "1534"
}
]
},
```

**Comment by asturcon** [comment]
> Questions
Does it make sense to have 2 endpoints for this ? Is this to be considered equivallent of dataset vs dataset/search? If so should we call it search instead of query?
https://api.gbif-dev.org/v1/pipelines/process/running and
http://api.gbif-dev.org/v1/pipelines/process/running/query

For this it was separated to keep the 2 versions running (and the _query_ name to avoid it to be cached). But now I can merge them, so you have only the endpoint https://api.gbif-dev.org/v1/pipelines/process/running  and you can use the query parameters in this endpoint

**Comment by asturcon** [comment]
> It seems confusing to me that we have
> https://api.gbif-dev.org/v1/ingestion/history/8575f23e-f762-11e1-a439-00145eb45e9a/241
> and
> https://api.gbif-dev.org/v1/pipelines/history/8575f23e-f762-11e1-a439-00145eb45e9a/241
> 
> with almost the same info, but different field names. Do we need both?
> 
> ```
> {
> "key": 10618,
> "datasetKey": "8575f23e-f762-11e1-a439-00145eb45e9a",
> "datasetTitle": "PonTaurus collection",
> "attempt": 241,
> "created": "2019-12-09T09:22:32.531033",
> "createdBy": "crawler.gbif.org",
> "executions": [
> {
> "key": 3084,
> "stepsToRun": [
> "TO_VERBATIM"
> ],
> "rerunReason": "ss",
> "created": "2019-12-10T16:52:01.060453",
> "createdBy": "mlopezg",
> "steps": [
> {
> "key": 11459,
> "type": "XML_TO_VERBATIM",
> "runner": "STANDALONE",
> "started": "2019-12-10T16:52:01.633",
> "finished": "2019-12-10T16:52:04.698",
> "state": "COMPLETED",
> "message": "{\"datasetUuid\":\"8575f23e-f762-11e1-a439-00145eb45e9a\",\"attempt\":241,\"totalRecordCount\":1534,\"reason\":\"NORMAL\",\"pipelineSteps\":[\"HDFS_VIEW\",\"INTERPRETED_TO_INDEX\",\"XML_TO_VERBATIM\",\"VERBATIM_TO_INTERPRETED\"],\"endpointType\":\"BIOCASE\",\"platform\":\"ALL\",\"executionId\":3084}",
> "numberRecords": 1534,
> "createdBy": "crawler.gbif.org",
> "modified": "2019-12-10T16:52:04.700077",
> "modifiedBy": "crawler.gbif.org",
> "metrics": [
> {
> "name": "archiveToErCount",
> "value": "1534"
> }
> ]
> },
> ```
> 
> vs
> 
> ```
> {
> "datasetKey": "8575f23e-f762-11e1-a439-00145eb45e9a",
> "datasetTitle": "PonTaurus collection",
> "attempt": 241,
> "crawlInfo": {
> "datasetKey": "8575f23e-f762-11e1-a439-00145eb45e9a",
> "crawlJob": {
> "datasetKey": "8575f23e-f762-11e1-a439-00145eb45e9a",
> "endpointType": "BIOCASE",
> "targetUrl": "http://ww3.bgbm.org/biocase/pywrapper.cgi?dsa=pontaurus",
> "attempt": 241,
> "properties": {}
> },
> "startedCrawling": "2019-12-09T09:21:48.121+0000",
> "finishedCrawling": "2019-12-09T09:22:32.060+0000",
> "finishReason": "NORMAL",
> "processStateOccurrence": "FINISHED",
> "processStateChecklist": "EMPTY",
> "pagesCrawled": 28,
> "pagesFragmentedSuccessful": 28,
> "pagesFragmentedError": 0,
> "fragmentsEmitted": 1534,
> "fragmentsReceived": 1534,
> "rawOccurrencesPersistedNew": 1534,
> "rawOccurrencesPersistedUpdated": 0,
> "rawOccurrencesPersistedUnchanged": 0,
> "rawOccurrencesPersistedError": 0,
> "fragmentsProcessed": 1534,
> "verbatimOccurrencesPersistedSuccessful": 1534,
> "verbatimOccurrencesPersistedError": 0,
> "interpretedOccurrencesPersistedSuccessful": 1534,
> "interpretedOccurrencesPersistedError": 0
> },
> "pipelineExecutions": [
> {
> "key": 3084,
> "stepsToRun": [
> "TO_VERBATIM"
> ],
> "rerunReason": "ss",
> "created": "2019-12-10T16:52:01.060453",
> "createdBy": "mlopezg",
> "steps": [
> {
> "key": 11459,
> "type": "XML_TO_VERBATIM",
> "runner": "STANDALONE",
> "started": "2019-12-10T16:52:01.633",
> "finished": "2019-12-10T16:52:04.698",
> "state": "COMPLETED",
> "message": "{\"datasetUuid\":\"8575f23e-f762-11e1-a439-00145eb45e9a\",\"attempt\":241,\"totalRecordCount\":1534,\"reason\":\"NORMAL\",\"pipelineSteps\":[\"HDFS_VIEW\",\"INTERPRETED_TO_INDEX\",\"XML_TO_VERBATIM\",\"VERBATIM_TO_INTERPRETED\"],\"endpointType\":\"BIOCASE\",\"platform\":\"ALL\",\"executionId\":3084}",
> "numberRecords": 1534,
> "createdBy": "crawler.gbif.org",
> "modified": "2019-12-10T16:52:04.700077",
> "modifiedBy": "crawler.gbif.org",
> "metrics": [
> {
> "name": "archiveToErCount",
> "value": "1534"
> }
> ]
> },
> ```

For this other question, let me think about it because now the https://api.gbif-dev.org/v1/pipelines/history is not very useful, so maybe I redesign it.

**Comment by asturcon** [comment]
> > Questions
> > Does it make sense to have 2 endpoints for this ? Is this to be considered equivallent of dataset vs dataset/search? If so should we call it search instead of query?
> > https://api.gbif-dev.org/v1/pipelines/process/running and
> > http://api.gbif-dev.org/v1/pipelines/process/running/query
> 
> For this it was separated to keep the 2 versions running (and the _query_ name to avoid it to be cached). But now I can merge them, so you have only the endpoint https://api.gbif-dev.org/v1/pipelines/process/running and you can use the query parameters in this endpoint

@MortenHofft I have this ready in a branch but if I merge it the current UI will break because the response in different. I suggest that you use the `/query` endpoint for now and then I'll merge it and you just need to remove the `/query` part from the endpoint (this will probably happen in January after vacations). 

I will also add 2 new fields to the response: offset and limit.

**Comment by MortenHofft** [comment]
> l also add 2 new fields to the response: offset and limit.

Nice - could you also make it similar to the other search endpoints. That is
```
count: 123, //currently it is called totalHits
limit: 10, //currently not there
offset: 20, //currently not there
results: []
```

**Comment by MortenHofft** [comment]
I'm closing this issue as these the interface for this has been rebuild entirely since the issue was created. And endpoints in the issue do not work anymore. @marcos-lg pleas elet me know if I'm missing out on a real issue here.

**Comment by marcos-lg** [comment]
This was just to add filters in the UI for:
- dataset key
- dataset title
- status
- step

I had created an endpoint but it seems that we broke it at some point and only works if you pass all the parameters (I'll fix it):

 http://api.gbif.org/v1/pipelines/process/running/query?status=RUNNING&datasetKey=f829b21c-976f-4e62-bad6-46d05af311f6&step=HDFS_VIEW&datasetTitle=test&offset=0&limit=10

Anyway, I don't know if we still want to add these filters to the UI or not.
