### ISSUE TITLE
Comments should require authentication to read

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#32]
Comments are readable by everyone from the API, but in the interface we do not want to show these unless you are logged in and have admin rights to this item. If the user do not have admin rights, the tab shouldn't show and neither should the comments.

https://gbif-registry-demo.netlify.com/organization/f5762dc1-b5af-496d-8f13-fdd7495d2cf4/comment

**Comment by luckyluck** [comment]
Added rules for menu and added check for a router. Could you please check it?
