### ISSUE TITLE
inline explanation desired

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#33]
https://github.com/gbif/registry-console/blob/b3857902e34f419164a664f85df1fca71babb085/src/components/common/CommentList/index.js#L161

I'm not familiar with `wrappedComponentRef` from antd and rc-form. Could you please add a comment in the text explaining its usage and a link to the documentation. When just seeing it is looks odd as it isn't a property that is explicitly used on the `CommentCreateForm` component.

**Comment by luckyluck** [comment]
I took this implementation from the official documentation, [From Section](https://ant.design/components/form/). Please, check the part "Form in Modal toCreate". I would add the same information. Also, here is a more detailed explanation: "If you want to get ref after Form.create, you can use _wrappedComponentRef_ provided by _rc-form_，[details can be viewed here](https://github.com/react-component/form#note-use-wrappedcomponentref-instead-of-withref-after-rc-form140)."

**Comment by MortenHofft** [comment]
Yes i gathered that, but could you please add it as a comment in the file. It makes it easier to understand. It is a very library specific thing, that a new developer wouldn't be able to guess easily I find. At least I couldn't

**Comment by luckyluck** [comment]
Got rid of that confusing parameter.
