### ISSUE TITLE
Add to the UI the new API fields in collections

### ISSUE THREAD

**Issue by marcos-lg** [gbif/registry-console#336]
New fields added in institutions:
- alternativeCodes: object where the key is the code and the value a description (http://api.gbif-dev.org/v1/grscicoll/institution/f4dac4e9-f45e-49ec-9e30-eb245ec8c8bd). It's only populated in DEV so far.

New fields added in collections:
- alternativeCodes: same as in institutions
- taxonomicCoverage: String
- geography: String
- notes: String
- incorporatedCollections: list of strings
- importantCollectors: list of strings
- collectionSummary (it is a list of key-value pairs): object where the values are numbers (see this http://api.gbif.org/v1/grscicoll/collection/46b062cf-f347-4e13-bdca-850dcf477eab)

This collection has most of these new fields populated: http://api.gbif.org/v1/grscicoll/collection/4777fd82-eace-4d9d-ba10-8bc1dabb2d6a

**Comment by asturcon** [comment]
Also we have to add comments to collections, institutions and persons (https://github.com/gbif/registry/issues/197).

**Comment by asturcon** [comment]
I'm currently doing this too one too https://github.com/gbif/registry/issues/179 so this issue can wait till I finish it so all the changes can be applied at once.

**Comment by asturcon** [comment]
This is in PROD now too https://github.com/gbif/registry/issues/179
