### ISSUE TITLE
Ordering of running crawls not stable

### ISSUE THREAD

**Issue by MattBlissett** [gbif/registry-console#346]
A while ago, I tried to change the column for ordering to "Start time", after we removed most of the other columns: https://github.com/gbif/registry-console/commit/5aa667a78848f1eb0e1eafb59f4ed2f48ca8aa59 (is .startedCrawling not an integer?)

This ought to be stable, but I must have done something wrong, as the ordering no longer works.

**Comment by MortenHofft** [comment]
the date is a string
