### ISSUE TITLE
Registry console adds unnecessary Authorization: headers

### ISSUE THREAD

**Issue by MattBlissett** [gbif/registry-console#347]
Requests to occurrence/search on the crawl-monitor view can fail when an Authorization: header is added by the registry-console:

```
GET https://api.gbif.org/v1/occurrence/search?limit=0&datasetKey=f4419c70-614f-11e2-897a-00145eb45e9a HTTP/2.0
…
Authorization: Bearer XXXXXXX
```

**Comment by MortenHofft** [comment]
The registry console currently add auth headers to all gbif api calls. 
* The benefit being that the jwt token is renewed (else it would expire in 30 minutes). 
* The downside that it is also a bit silly and likely unneccessary to renew the token that way.

**Comment by MortenHofft** [comment]
I don't think the API should fail over for this reason, but it has now been removed
