### ISSUE TITLE
Display type of error

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#350]
Hi it would be great if the UI could display the type of error we get (for example: EMAIL_ALREADY_IN_USE).
Right now the message I get is "An error occurred".

**Comment by MortenHofft** [comment]
where is this happening please? the actions performed I mean. 

I might be able to show it. We aren't consistent in the error response formats. sometimes it is html, other times plain text other times json, but I can try. seems very reasonable.

**Comment by ManonGros** [comment]
In this case, a user requested that we update their email address (https://registry.gbif.org/user) but there was already an account associated with the "new" email.
I hadn't realised this was the case and didn't understand why I couldn't update the email address.

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/registry-console/commit/0d173e74e4193875358c2419c179b22e9bb6137b
