### ISSUE TITLE
UI shows modification date as deleted date

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#352]
I just deleted this dataset: http://api.gbif-uat.org/v1/grscicoll/institution/9caa147d-279a-4ce2-bda0-3d3b19a2fedc
But the UI shows a deletion 6 months ago (which corresponds to the "modified" date): https://registry.gbif-uat.org/institution/9caa147d-279a-4ce2-bda0-3d3b19a2fedc

**Comment by marcos-lg** [comment]
Fixed in the API to update the modified date when there is a deletion (it was only happening with the new merge service)
