### ISSUE TITLE
GrSciColl UI - allow founding date to be just a year

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#356]
The founding date that people send is often just something like "1927". I don't know if I am doing something wrong but I can't select just a year via the calendar box.

**Comment by MortenHofft** [comment]
@marcos-lg what is the constraints on this field. I see that it returns dates
https://registry-api.gbif-uat.org/grscicoll/institution/fa252605-26f6-426c-9892-94d071c2c77f
`"foundingDate": "1852-01-01T00:00:00.000+0000"`

**Comment by marcos-lg** [comment]
@MortenHofft it's just a date (as the other dates we have, e.g.:created or modified)

**Comment by MortenHofft** [comment]
@ManonGros so the question is if we want this to be a date field or simply a string

**Comment by MortenHofft** [comment]
How about changing it to founding year and make it a number? Do we thing we loose to much information by not having the exact date (is it ever present?)

**Comment by ManonGros** [comment]
Thanks @MortenHofft I dropped the ball on this issue.
I know that the Japanese Node manager has been adding specific dates.

I don't know what would be best honestly (date or string or year with number). I logged this issue without realising what the implications were.
I guess the question is whether we expect our users to search institutions by founding date/year. If that was a use case, then we should probably avoid a string field.
I guess we could keep the date field and have a second "founding year" field. But I am not sure this would be a good idea, it might just make everything more confusing.
What do you think?

**Comment by MortenHofft** [comment]
> What do you think?

I think it should be a string or an integer, but I'm not sure which. I would start with integer and see if anyone complains that they can tell the rich story of their founding date with just that.

**Comment by ManonGros** [comment]
Ok sounds good to me. So a year field with an integer would be needed.

**Comment by MortenHofft** [comment]
@marcos-lg could you please assign this to me when/if the API changes. Then I will update the UI to use integers as well

**Comment by MortenHofft** [comment]
@marcos-lg I believe this is ready for implementation. Let me know if you have any concerns
