### ISSUE TITLE
review create logic

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#366]
@marcos-lg and @manongros
I'm in the process of rewritting our permissions. The backend do not provide a way for me to evaluate wether a user has create access ahead of actually creating it. So for that part there is still client logic. Could you help me evaluate if this is correct please? 
https://github.com/gbif/registry-console/blob/permissions/src/components/auth/userUtil.js#L73

```js
function getRights(user, _scopeTypes) {
  let userRights = [];
  // if a user has a node in their scope, then they should be allowed to create org + datasets (there might be restrictions on what the content of that entity is)
  if (_scopeTypes.includes(entityTypes.NODE)) {
    userRights.push(rights.CAN_ADD_ORGANIZATION);
    userRights.push(rights.CAN_ADD_DATASET);
  }
  if (_scopeTypes.includes(entityTypes.ORGANIZATION)) {
    userRights.push(rights.CAN_ADD_DATASET);
  }
  // if a user has a grscicoll role, then they can create entities (again there might be restrictions on what the content of that entity is)
  if (_intersection(user.roles, [roles.GRSCICOLL_ADMIN, roles.GRSCICOLL_EDITOR])) {
    userRights.push(rights.CAN_ADD_COLLECTION);
    userRights.push(rights.CAN_ADD_INSTITUTION);
    userRights.push(rights.CAN_ADD_GRSCICOLL_PERSON);
  }
  if (_intersection(user.roles, [roles.REGISTRY_ADMIN])) {
    userRights.push(rights.CAN_ADD_NETWORK);
    userRights.push(rights.CAN_ADD_INSTALLATION);
    userRights.push(rights.CAN_ADD_ORGANIZATION);
    userRights.push(rights.CAN_ADD_DATASET);
  }
  return _uniq(userRights);
}
```

**Comment by ManonGros** [comment]
Thanks @MortenHofft 

I think we are missing a few things:
* Node and organization editors should be able to create installations as well (at least that's how it is working right now with Symbiota)
* I think we now have the IDIGBIO_GRSCICOLL_EDITOR role, @marcos-lg could you confirm? They should also be allowed to create collections, institution, staff.

So if I understand the code correctly, it should be:
```
function getRights(user, _scopeTypes) {
  let userRights = [];
  // if a user has a node in their scope, then they should be allowed to create org + datasets + installation (there might be restrictions on what the content of that entity is)
  if (_scopeTypes.includes(entityTypes.NODE)) {
    userRights.push(rights.CAN_ADD_ORGANIZATION);
    userRights.push(rights.CAN_ADD_DATASET);
    userRights.push(rights.CAN_ADD_INSTALLATION);
  }
  if (_scopeTypes.includes(entityTypes.ORGANIZATION)) {
    userRights.push(rights.CAN_ADD_DATASET);
    userRights.push(rights.CAN_ADD_INSTALLATION);
  }
  // if a user has a grscicoll role, then they can create entities (again there might be restrictions on what the content of that entity is)
  if (_intersection(user.roles, [roles.GRSCICOLL_ADMIN, roles.GRSCICOLL_EDITOR, roles. IDIGBIO_GRSCICOLL_EDITOR])) {
    userRights.push(rights.CAN_ADD_COLLECTION);
    userRights.push(rights.CAN_ADD_INSTITUTION);
    userRights.push(rights.CAN_ADD_GRSCICOLL_PERSON);
  }
  if (_intersection(user.roles, [roles.REGISTRY_ADMIN])) {
    userRights.push(rights.CAN_ADD_NETWORK);
    userRights.push(rights.CAN_ADD_INSTALLATION);
    userRights.push(rights.CAN_ADD_ORGANIZATION);
    userRights.push(rights.CAN_ADD_DATASET);
  }
  return _uniq(userRights);
}
```

**Comment by marcos-lg** [comment]
The `IDIGBIO_GRSCICOLL_EDITOR` still can't really do anything, only merging iDigBio entities. It's still under discussion what they should be able to do (https://github.com/gbif/registry/issues/296)

**Comment by dagendresen** [comment]
If this is the correct issue to add this comment (registry permission logic) -- I am GBIF Norway Node Manager and can add new identifiers for Norwegian institutions to the registry (data publishers, not GrSciColl) -- but only as endpoint type "URI" and get an error message when adding as type "Grid" or "ROR" (tried different variations of the Grid and ROR identifier string). Example: https://registry.gbif.org/organization/819352ad-c630-44e6-9356-d2c7aaf9866d/identifier

**Comment by MortenHofft** [comment]
Hi @dagendresen 
I created a new issue based on your comment https://github.com/gbif/registry/issues/312

It is unrelated to the discussion here, but i can reproduce your issue and do not see it working either.

**Comment by MortenHofft** [comment]
This logic is now delegated to the server. So this issue can be closed
