### ISSUE TITLE
nodes cannot be created

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#37]
The current registry has an option to create nodes. I don't think that should be there in the new system as we have another system to handle that. @timrobertson100 do you agree? Node management belongs in the directory doesn't it?

**Comment by luckyluck** [comment]
@MortenHofft , can I remove all files for Nodes or it's better to keep it as it is?

**Comment by MortenHofft** [comment]
the registry should not create or edit nodes - you can remove it. Nodes are read only.

**Comment by luckyluck** [comment]
Done!
