### ISSUE TITLE
UI shows all institutions and collections on the GRSciColl staff pages

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#370]
This is what I mean:
<img width="1084" alt="Screenshot 2021-02-25 at 14 27 05" src="https://user-images.githubusercontent.com/7677271/109160128-af3fb900-7775-11eb-84aa-952942522201.png">

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/registry-console/commit/461221683df975bdd9238548ba0f36e14a30cb4f
