### ISSUE TITLE
Vocabulary concepts shows 0 when there are some

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry-console#375]
Clicking on any vocabulary can often show 0 concepts when there are actually concepts. I think this happens when you revisit the vocabulary a second time.

To reproduce:
- https://registry.gbif.org/vocabulary/search
- click lifestage and it may show N concepts if it shows 0 you've seen the bug
- if not click a concept, then at the breadcrumb go back, choose another vocabulary and keep repeating until you see it show 0. It happens regularly enough for me that you'll see it within 3 passes.

**Comment by MortenHofft** [comment]
Sounds like the same as this issue https://github.com/gbif/registry-console/issues/358
