### ISSUE TITLE
Suggest a change

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#376]
@ManonGros I wondered about the suggest a change functionality this morning. What is the minimum requirements and what is the perfect solution as you see it?

**Comment by MortenHofft** [comment]
Could a simple solution be to allow anyone (perhaps they have to be logged in) to suggest a change (possibly along with an explanation and contact email).

That could then be stored in Github as a comparison table. Along with a label like `grscicoll change suggestion`

And there could be a link to the registry where you could see the change, possible edit it and store it. 

Field | Changed | Original | Change
-----|---|------|------
code| X | "AGM"|"AGMT"
etc|||

[See change in registry](https://registry.gbif-uat.org/collection/dc4a4529-faac-4dc9-be6a-2800ba7903c8?suggestion=sdfkhjgsdkfjhg)

I'm not sure how well it would work. The tables would be quite large.  @timrobertson100 you mentioned storing this in Github for everyone to see it and as a solution that was almost purely frontend work - hence this suggestion. Did you have something else in mind?

**Comment by MortenHofft** [comment]
More realistic table examples with nonsense data

Field | Changed | Original | Change
-----|---|------|------
key| | "36e74642-41e9-47af-9103-383742bea611"|"36e74642-41e9-47af-9103-383742bea611"
code| | "AGMT"|"AGMT"
name| | "Associazione Gruppi Micologici Toscani"|"Associazione Gruppi Micologici Toscani"
description| | "Lorem markdownum facunde, libidine fassaque Talia vento tua habebit numerodignare dum locum visa lascivaque Hecaten, sub sed. *Paulumque* matris**pullosque verso ore**, illi quas latus. Tenebrae pulsata, haec huic tela dum,patulis solet quaerere velle, convivia ille et? Post et nec eris dederis est:felicem ut mihi sine rogat *potente*, ullo primo neque. Humum facies meque,spatium revocare suspenderat omnes ceu litore silvas patres, tertius*virilibus*!"|"Lorem markdownum facunde, libidine fassaque Talia vento tua habebit numerodignare dum locum visa lascivaque Hecaten, sub sed. *Paulumque* matris**pullosque verso ore**, illi quas latus. Tenebrae pulsata, haec huic tela dum,patulis solet quaerere velle, convivia ille et? Post et nec eris dederis est:felicem ut mihi sine rogat *potente*, ullo primo neque. Humum facies meque,spatium revocare suspenderat omnes ceu litore silvas patres, tertius*virilibus*!"
contentTypes| | ["ARCHAEOLOGICAL_OTHER","ARCHAEOLOGICAL_FLORAL_REMAINS","ARCHAEOLOGICAL_CERAMIC_ARTIFACTS","ARCHAEOLOGICAL_FLORAL_ARTIFACTS","ARCHAEOLOGICAL_METAL_ARTIFACTS"]|["ARCHAEOLOGICAL_OTHER","ARCHAEOLOGICAL_FLORAL_REMAINS","ARCHAEOLOGICAL_CERAMIC_ARTIFACTS","ARCHAEOLOGICAL_FLORAL_ARTIFACTS","ARCHAEOLOGICAL_METAL_ARTIFACTS"]
active| | true|true
personalCollection| | true|true
email| | ["erbario@agmtmicologia.org","sdfg@sdfg.gh"]|["erbario@agmtmicologia.org","sdfg@sdfg.gh"]
phone| | ["3287689710","23452345"]|["3287689710","23452345"]
homepage| | "http://www.agmtmicologia.org"|"http://www.agmtmicologia.org"
catalogUrl| | "http://www.agmtmicologia.org"|"http://www.agmtmicologia.org"
apiUrl| | "http://www.agmtmicologia.org"|"http://www.agmtmicologia.org"
preservationTypes| | ["STORAGE_INDOORS","STORAGE_FROZEN_MINUS_80","STORAGE_FROZEN_BETWEEN_MINUS_132_AND_MINUS_196"]|["STORAGE_INDOORS","STORAGE_FROZEN_MINUS_80","STORAGE_FROZEN_BETWEEN_MINUS_132_AND_MINUS_196"]
accessionStatus| | "INSTITUTIONAL"|"INSTITUTIONAL"
institutionKey| | "5ed4ae5a-4638-4c61-8af1-b476f64bc0a2"|"5ed4ae5a-4638-4c61-8af1-b476f64bc0a2"
mailingAddress| | {"key":42163,"address":"Via Turi 8","city":"Santa Croce sull'Arno","province":"provin","country":"IT"}|{"key":42163,"address":"Via Turi 8","city":"Santa Croce sull'Arno","province":"provin","country":"IT"}
address| | {"key":42162,"address":"Via Turi 8","city":"Santa Croce sull'Arno","country":"IT"}|{"key":42162,"address":"Via Turi 8","city":"Santa Croce sull'Arno","country":"IT"}
createdBy| | "mhoefft"|"mhoefft"
modifiedBy| | "mhoefft"|"mhoefft"
created| | "2020-12-17T19:45:08.193+00:00"|"2020-12-17T19:45:08.193+00:00"
modified| | "2021-04-08T08:44:57.180+00:00"|"2021-04-08T08:44:57.180+00:00"
tags| | []|[]
indexHerbariorumRecord| | false|false
numberSpecimens| | 0|0
machineTags| | []|[]
taxonomicCoverage| | "asdfkjhg asdfb sdfkja gsdfo7iy gewkjhfdg o7aiwe fdlkha sldiouf alsydgf kajhsdgf kjhags df"|"asdfkjhg asdfb sdfkja gsdfo7iy gewkjhfdg o7aiwe fdlkha sldiouf alsydgf kajhsdgf kjhags df"
geography| | "aaaaa bbbbb aaaa"|"aaaaa bbbbb aaaa"
notes| | "asdhfg yuaksgd fkhjagsd kfjhg"|"asdhfg yuaksgd fkhjagsd kfjhg"
incorporatedCollections| | ["asdflh asdfhg kjhg asdf","qwieur gfjhdgf fkaygf dkjhg aadsf"]|["asdflh asdfhg kjhg asdf","qwieur gfjhdgf fkaygf dkjhg aadsf"]
importantCollectors| | ["robert","sara"]|["robert","sara"]
collectionSummary| | {}|{}
alternativeCodes| | [{"code":"ABC","description":"something goes here"},{"code":"DBA","description":"something else"}]|[{"code":"ABC","description":"something goes here"},{"code":"DBA","description":"something else"}]
comments| | []|[]
occurrenceMappings| | []|[]
institutionName| | "Swedish Museum of Natural History - Zoological Collections"|"Swedish Museum of Natural History - Zoological Collections"
institutionCode| | "NRM"|"NRM"

Seems we could also have nested tables

|                |ASCII                          |HTML                         |
|----------------|-------------------------------|-----------------------------|
|Single backticks|`'Isn't this fun?'`            |'Isn't this fun?'            |
|Quotes          |`"Isn't this fun?"`            |<table>  <thead>  <tr>  <th></th>  <th>ASCII</th>  <th>HTML</th>  </tr>  </thead>  <tbody>  <tr>  <td>Single backticks</td>  <td><code>'Isn't this fun?'</code></td>  <td>‘Isn’t this fun?’</td>  </tr>  <tr>  <td>Quotes</td>  <td><code>"Isn't this fun?"</code></td>  <td>“Isn’t this fun?”</td>  </tr>  <tr>  <td>Dashes</td>  <td><code>-- is en-dash, --- is em-dash</code></td>  <td>– is en-dash, — is em-dash</td>  </tr>  </tbody>  </table>      |
|Dashes          |`-- is en-dash, --- is em-dash`|-- is en-dash, --- is em-dash|

**Comment by ManonGros** [comment]
Thanks @MortenHofft!
I don't think reviewing the changes on a big table like that would be very practical.
Perhaps if it showed just the fields that changed. Or perhaps if it was more like a GH file comparison where the lines changed are on above the other and the changed content highlighted?
<img width="726" alt="Screenshot 2021-04-08 at 13 59 11" src="https://user-images.githubusercontent.com/7677271/114023100-c09adb80-9872-11eb-84a7-427ce3a387b9.png">

The ideal experience for me would be something like that:

1. I get a notification that someone made a new suggestion (it could be just a GH issue notification in a repo),
2. I can see who proposed those changes (I think having people log in GBIF.org is a good idea but if they don't have a GBIF account, we could consider just asking for their name and email.)
3. I can review the old and new information side by side and the changes are highlighted.
4. I can potentially edit the proposed change if needed.
5. I can click one button and the changes are implemented in the registry.

I understand that this might not be possible. 
A table with just the field changed, the person who request the changes and a link to the original record in the registry would be the minimum. It would be better than to have the changes described in an email.

**Comment by MortenHofft** [comment]
Which entities would this be for?
collection and institution core fields (not contacts, identifiers, tags, comments etc)? Or is contacts included (that makes it more difficult as far as I can tell)

**Comment by ManonGros** [comment]
I think we should do it for collection and institution core fields.

I can see how doing that for the contacts would be complicated.
That being said, contacts are the most likely to change and to need updating. It would be nice to have some structured way for users to notify us of those contact changes. But at the same time, we might want to wait until we have a better idea of the work we will need to do with Staff (https://github.com/gbif/registry/issues/321).

Perhaps what we should have a policy of "only (institution/collection) editors can update the staff"? So this "suggest a change" form would be for the collection and institution core fields, and would notify the users they can contact us to become editors on behalf of their institutions if they want to update the contacts?
Maybe I am over-thinking this. @ahahn-gbif, do you have any thought on this topic?

**Comment by ahahn-gbif** [comment]
I agree that contact data work flows may be best discussed / decided around or after the overall staff data decisions. In general I would agree that institutions should be best placed to know/curate their staff data. although I am not sure we will get all of them actively involved. 

UI wise, maybe allowing feedback requesting to switch a staff entry _off_ could help to de-clutter, even if adding new contacts might still be a bit further down the line? Especially if it is only a logical deletion for a start, so it is reversible if needed? I am unsure about verification procedures needed (e.g. do we need to check email bounces?). Just thinking out loud here.

**Comment by MortenHofft** [comment]
I've implemented the simplest solution I could come up with and put in on UAT
e.g. https://registry.gbif-uat.org/collection/1d4431c7-f078-4f15-89c1-6dfb0cb4f939

If you are not logged in you will still see the edit button
You are informed that you have to have a GitHub account.
When clicking save you are redirected to GitHub with a prefilled issue
That issue shows a summary of the changes and a link back to the registry with the changes filled into the form (and any changes highlighted again)
The reviewer can then edit or simply save the suggested change.

To avoid requiring users to have a Github account, then we could have a proxy like we do for feedback on gbif.org, that would also ensure that the summary and link back to the registry isn't fiddled with.

**Comment by MortenHofft** [comment]
example issue
-----







**name**
~~`my collection`~~
`my collection changed text`

**description**
~~`sdf`~~
<pre><code>sdf
more
lines</code></pre>

**contentTypes**
<pre><code><del>[
  "ARCHAEOLOGICAL_OTHER"
]</del></code></pre>
<pre><code>[
  "ARCHAEOLOGICAL_OTHER",
  "ARCHAEOLOGICAL_HUMAN_REMAINS"
]</code></pre>


https://registry.gbif-uat.org/collection/1d4431c7-f078-4f15-89c1-6dfb0cb4f939?suggestion=%7B%22name%22%3A%22my%20collection%20changed%20text%22%2C%22description%22%3A%22sdf%5Cnmore%5Cnlines%22%2C%22contentTypes%22%3A%5B%22ARCHAEOLOGICAL_OTHER%22%2C%22ARCHAEOLOGICAL_HUMAN_REMAINS%22%5D%7D

**Comment by ManonGros** [comment]
Thanks @MortenHofft it looks great! I like how simple it is and how the changes are highlighted.
I have two comments/ideas:
* For changes that are not available via this system (contact, identifier, merging...) it would be good to remind users where to contact us. Something like "To update anything else, please contact us at scientific-collections@gbif.org". What do you think?
* Could something similar to this "suggest a change" system be used to create new entries? So people could suggest adding new institution and collections.

> To avoid requiring users to have a Github account, then we could have a proxy like we do for feedback on gbif.org, that would also ensure that the summary and link back to the registry isn't fiddled with.

I think this would be great! Would it be be doable?

**Comment by MortenHofft** [comment]
> I think this would be great! Would it be be doable?

Redirecting through GBIF.org is relatively simple to add. And adding new entries, text changes etc should be is simple to add. This was just intended to start the conversation to see if it is going in the right direction.

Another approach would be that we created a backend to manage this instead of using Github as our data store. I would prefer to hear what @timrobertson100 think of it before proceeding

**Comment by timrobertson100** [comment]
This looks really impressive.

Github is nice as it allows external commentary, but it might prove more robust to have a dedicated backend. 

I can imagine we also wish to keep an audit log of all edits, so having a "before" and "after" view of records either as a proposed change, or an applied change might be something to implement together. The UI part of this looks fabulous though.

**Comment by MortenHofft** [comment]
Current API specs are here in a temporary format https://gist.github.com/marcos-lg/02bf4356ba7fee2ae74ae15cc10f91a4
