### ISSUE TITLE
Predictive text issue - Vocabulary / Alternative labels

### ISSUE THREAD

**Issue by leobuitrago2** [gbif/registry-console#377]
When you are typing in the _Language_ drop-down list of the '**Alternative labels**' the behaviour is strange and you don't get clear choices from your request. See the image... 
![Screen Shot 2021-04-08 at 6 33 12 PM](https://user-images.githubusercontent.com/80980518/114110082-4bdc9700-989c-11eb-83c6-402c09b60a61.png)

In the end, you can go down on the list and select the language you want, but this is not what you expect from a drop-down list with predictive text.

**Comment by MortenHofft** [comment]
Same as the closed https://github.com/gbif/registry-console/issues/324
The issue is as far as I can see that it does the autocomplete on the language codes instead of the translated values
