### ISSUE TITLE
Cannot save edit on dev

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#380]
This is the example I used: https://registry.gbif-dev.org/collection/1068ecb2-a296-4684-beab-937111253487
I was logged in with my editor account (that has permissions for US GRSciColl entities).
I can click on edit and add content but when I click on save, nothing seems to happen.
But if I click on cancel and refresh the page, the modifications appear.

**Comment by MortenHofft** [comment]
This was addressed in https://github.com/gbif/registry-console/commit/21c418bcd90fea37923856ce869f08a3707ea0bf
