### ISSUE TITLE
Cannot save suggestion with empty description if I put and removed character

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#384]
I was testing the suggest a change in UAT on an institution.
I tried suggesting a change and accidentally put something in the empty description and then removed it. This prevented me from saving the suggestion. I got the error message: `Validation of [description] failed: size must be between 1 and 2147483647`.

However, if I don't touch the description field at all, I can save the suggestion with the empty description.

**Comment by MortenHofft** [comment]
@marcos-lg the UI sends an empty string instead of null when the user has interacted with the field. Could you handle this in in the backend instead? Or would you prefer the frontend to remove empty strings?

**Comment by marcos-lg** [comment]
I'd prefer that for now you handle it in the frontend since that's a common behaviour we have in the api

**Comment by MortenHofft** [comment]
I just tried - it is perfectly possible to edit a collection with an empty string as a description

**Comment by ManonGros** [comment]
I can also edit the description to be an empty string. This happens only with suggestions somewhow:
<img width="957" alt="Screenshot 2021-06-10 at 14 24 52" src="https://user-images.githubusercontent.com/7677271/121524919-15d0a600-c9f8-11eb-8dc9-fff1493b4e16.png">

**Comment by marcos-lg** [comment]
Fixed in DEV. Will be in PROD next week.

**Comment by marcos-lg** [comment]
Deployed in PROD.
