### ISSUE TITLE
GRSciColl - user permission administration - add country and machineTage namespace

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#388]
With the new permission model for GRSciColl, we now have country and machineTage namespace scopes.
Right now I am administrating our user's permission for those scopes with the API.
It would be nice if I could do it in the UI (although not urgent at all).

**Comment by ManonGros** [comment]
@MortenHofft I think this is becoming more important so that users can see if they have the GRSciColl permission for a specific country: https://github.com/gbif/portal-feedback/issues/3488

**Comment by MortenHofft** [comment]
@ManonGros This seem related to https://github.com/gbif/registry/issues/232 should that issue be closed?

@marcos-lg can you please remind me where to find the documentation for this please?

**Comment by marcos-lg** [comment]
We actually don't have documentation for these endpoints. The endpoints we have are these:

- GET /admin/user/{username}/namespaceRight
- POST /admin/user/{username}/namespaceRight -> the body contains the namespace( I think it only works with TEXT_PLAIN)
- DELETE /admin/user/{username}/namespaceRight/{namespace}

- GET /admin/user/{username}/countryRight
- POST /admin/user/{username}/countryRight -> the body contains the 2-letter iso code of the country ( I think it only works with TEXT_PLAIN)
- DELETE /admin/user/{username}/countryRight/{countryParam}

Also, in the search we have these new 2 parameters (they work as editorRightsOn) to filter by namespaces and countries:
- namespaceRightsOn: list of namespaces
- countryRightsOn: list of countries in 2-letter iso code

These endpoints are only for admins.
