### ISSUE TITLE
Make registry UI multi-lingual

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#389]
We will be getting a Spanish translation of the GRSciColl fields, would it be possible to have them in the UI?

**Comment by MortenHofft** [comment]
yes, but some work or procedures is needed for managing the translations in Crowdin

**Comment by ManonGros** [comment]
Thanks! Is this something I can help with?

**Comment by MortenHofft** [comment]
I can set it up in Crowdin which kindly supports us. Then it can all be translated. If they only want to translate GrSciColl fields then it might be a bit tricky to locate those exact fields.

**Comment by ManonGros** [comment]
That would be great! I don't know exactly how crowding works, could we push incomplete translation? For example, if the translation concerns only GRSciColl, could we still show it in the interface?

Also, I am ver happy to translate everything to French.

**Comment by MortenHofft** [comment]
Incomplete translations will just show as e.g. part english part spanish. 
Another question: do we want metadata to be filled in other languages? Currently I think all metadata in GrSciColl is in english.

Is translating the UI important if we expect content to be provided in english anyhow? I get that many of the fields are largely language independent (address, code, homepage etc), but wouldn't we expect name and description to be provided in english?

**Comment by MattBlissett** [comment]
The CrowdIn project is https://crowdin.com/project/gbif-registry/

I thought I'd include the emails, since Mikhail set those up to be translatable, but there's an issue adding `.ftl` files into CrowdIn. I've asked them what can be done about that.

**Comment by MattBlissett** [comment]
The `.ftl` email template files are now translatable too.

**Comment by MortenHofft** [comment]
The UI has changed to show french in dev and uat.

This is the flow Marie:
* You do a change in crowdin
* The change gets synced to its own branch with some fixed internal (every 10 minutes). 
* I (or someone else) will then have to do a merge into the master branch.
* That will automatically trigger a deployment to dev. To make it available in other environments we have to do a deployment manually.

**Comment by MortenHofft** [comment]
Let me know which languages the UI should include. And when they should go to production.

**Comment by MortenHofft** [comment]
@ManonGros currently the project is setup to delete translations if the english source string changes.
What behaviour do you prefer. The options are:
* remove the translation
* keep the translation but mark it as unapproved (what we do in the gbif.org project)
* keep the translation.

https://support.crowdin.com/configuration-file/#changed-strings-update

**Comment by ManonGros** [comment]
Wonderful! Many thanks Morten!
Seeing the translation in the UAT will be very useful to double check it in the context. I already reached out to our Spanish GRSciColl translator and will be adding the Spanish translation as soon as I have it.

**Comment by ManonGros** [comment]
@MortenHofft I think option 1 is fine:
> remove the translation (registry project currently)

Is there a way I could be notified when that happens?

**Comment by MattBlissett** [comment]
"Notify translators about new strings" is ticked, but I don't know how it works.

**Comment by MortenHofft** [comment]
> "Notify translators about new strings" is ticked, but I don't know how it works.

Yes I just ticked that. I believe translators use that a lot on gbif.org. At least I have noticed that any new terms of translated very quickly at times.
