### ISSUE TITLE
missing help texts in grscicoll forms

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#404]
missing help texts from collections:

Personal collection
taxonomic coverage
geography
notes

**Comment by MortenHofft** [comment]
`RES API`
https://github.com/gbif/registry-console/blob/12d93902773f1d379b1636f56da90252d557fe33/locales/en.json#L1819

I assuem that should be a REST API? but does the API type really matter. isn't it just any API?

**Comment by MortenHofft** [comment]
`collection.Preservation types` says see link. which link?

**Comment by MortenHofft** [comment]
Also missing `help.collection.address.country`

**Comment by ManonGros** [comment]
Thanks @MortenHofft!
