### ISSUE TITLE
GRSciColl - make institution a mandatory field when creating collections

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#408]
We have had now a few suggestions to create collections where the parent institution wasn't provided. I can sometimes guess it but it would be easier if the field was mandatory (or highlighted?)

**Comment by MortenHofft** [comment]
We have many collections without an institution. That is the reason it is mandatory.
In theory we could make it mandatory when suggesting one, but currently it just reuse the same form as that is simplest.
