### ISSUE TITLE
Help text for alternative codes

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#415]
@ManonGros should we have some descriptive text for alternative codes to guide editors? I ask because I noticed the use on this record:

https://registry.gbif.org/institution/390f06b3-a81e-41b9-972e-e790e0edfe04

I notice that @dagendresen is putting identifiers into alternative codes. But we have structured identifiers for that. And had the identifiers been used, then I assume records like https://www.gbif.org/occurrence/1702253346 would have linked to that institution.

https://registry.gbif.org/institution/390f06b3-a81e-41b9-972e-e790e0edfe04
and
https://registry.gbif.org/institution/2e961f1c-399e-4aab-92ea-0657722f8dcd

looks a lot like duplicates btw.

**Comment by dagendresen** [comment]
I am not sure if I had access to add "identifiers" in GrSciColl previously -- and thus added as alt code. I have now added the identifiers as structured "identifiers" -- which I agree looks much better.

Some guideline info-text on the format -- with/without HTTP would be useful.

**Comment by MortenHofft** [comment]
Thanks Dag  - that is nice of you.
Most changes will be overwritten when we sync next time with IH (I believe we do so weekly).
But some fields are not modelled in IH and must therefor be edited in the GrSciColl/Registry.

A pending work item is to have an API that specify exactly which fields are controlled via IH (or other future master source) and which can/should be edited in GrSciColl/Registry

**Comment by ManonGros** [comment]
@MortenHofft @dagendresen, the current help text for alternative codes is the following:
> In addition to the primary institution Code, above: any additional code that is already in use for the same institution in other contexts (Index Herbariorum; self-representation; references used in published collection data etc) should be identified here

I am happy to update it. Should I specify that this is not the place for identifiers?

(also I suspect that this text wasn't available yet when Dag filled the institution information)

**Comment by dagendresen** [comment]
Thanks, my interest is rather primarily in the [identifiers](https://github.com/gbif/registry-console/issues/416) and less so on the codes.

**Comment by MortenHofft** [comment]
It sounds like this issue can be closed. @ManonGros let me know if we should update the help texts

**Comment by ManonGros** [comment]
I think we should eventually have some guidelines for the identifiers but I need to check with @ahahn-gbif.

@dagendresen I think with the http is a good idea as it will enable users to click on the links or at least know that these identifiers can be URLs. If you have any preference on the identifier format, now is the time to share it (before we write the guidelines). I suggest to open a new issue though.
