### ISSUE TITLE
editing alternative codes

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#419]
In an attempt to fix a typo in the alternative codes i discovered a bug in the UI
https://registry.gbif.org/institution/8ce2ae55-957d-4b70-bdf4-a077414bef76

For some "codes" it says:
code: ROR
description: 2345

and for others it would be
code: 3456
description: Grid

BUT, when trying to change it, it wouldn't allow me to edit the description. The UI would currently me require to delete it and add it again, instead of just editing it.

**Comment by ManonGros** [comment]
If I try to edit the description of an alternative code, everything goes blank. Do you get the same thing?

**Comment by MortenHofft** [comment]
Yes, but that is a new bug. Possibly the form rewritting issue again!

**Comment by thomasstjerne** [comment]
There was a `div` element wrapping the inputs of the AlternativeCodes component - this had to be changed to a React.Fragment `<>` instead.
