### ISSUE TITLE
GRSciColl - update UI to accommodate new contact model

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#420]
The new contact model is now implemented: https://github.com/gbif/registry/issues/379#issuecomment-953797110

The Registry UI needs to be updated to use the new model.

Right now there are 2 fields in collections and institutions:

contacts -> old model
contactPersons -> new model

the same for the endpoints, e.g.: https://api.gbif.org/v1/grscicoll/institution/a2e50ff3-62ae-419a-8749-455342e0b455/contactPerson

The IH synch will only update the contacts under the new model. And the suggestions accept contacts now.

We need the UI to:
- show the contacts from the new model
- enable editing under the new model
- enable contact suggestions

**Comment by MortenHofft** [comment]
This issue is better split into 2. 
* One for using the new model with the current functionalities of editing/deleting/creating.
* And another for supporting suggestions
