### ISSUE TITLE
allow suggestions to grscicoll contacts

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#426]
part of https://github.com/gbif/registry-console/issues/420

Once the UI has been rewritten to support the new contact model, then we should add support for suggestions of contacts (updates, deletion and creates). Similar to how we support it for collection and institutions core fields

**Comment by MortenHofft** [comment]
@ManonGros this is a larger task I believe - how would you evaluate the impact/usefulness?

**Comment by ManonGros** [comment]
As mentioned in our Slack chat, this is not the highest priority but it would be good to have on the long term.

**Comment by MortenHofft** [comment]
This has the potential to be very time consuming. I've implemented the simplest solution I could come up with. It isn't perfect in terms of Usability, nor is it wonderful in terms of code. But it was the simplest solution I could come up with. Anything more will likely require a more proper refactor of the code and possible another iteration of the APIs. The issue is that this scenario wasn't anywhere considered when the original code was written, and the suggest functionality is a patch that I added. And not a very pretty one.

@ManonGros  since you are the primary user of this, could you please let me know if this solution is frustrating for you?

In terms of UI:
For the users making suggestions they go to contacts. I think that is reasonable okay. 
The not so nice part is the reviewers where they have to look at JSON.

**Comment by ManonGros** [comment]
Thanks Morten! Aside from the issue I reported (suggestions not applying for me in dev), the user suggestion experience is pretty good.
I would update the text in the blue box. Maybe something like this:
> You do not have access to edit this entity, but you can leave a suggestion. Click 'Suggest' to edit individual fields **or update contacts in the 'Contacts' tab. Or 'More' for additional options. If you want to suggest an identifier, then please contact us per email.
> Suggest per email instead

The reviewer experience isn't ideal but it is manageable. Considering that most reviewers are relatively tech-savvy, I think this will be good enough.
