### ISSUE TITLE
Disconnect master source

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#429]
via https://github.com/gbif/registry-console/issues/379

> Something else to modify and this is a bit more complicated. Editors should still be given the possibility to "disconnect" an institution from IH. In practise, that means deleting the IH machineTag but we don't want editors to do it directly.
Ideally, what we need is some way for the UI to offer the possibility to disconnect from IH. I am not sure what would be the best way to implement that. We can discuss several possible solutions.

**Comment by MortenHofft** [comment]
It sounds like this should be more general than disconnection IH.

Like a way to define and remove master sources. So could also be to disconnect a dataset as master source.
Or to connect a publisher as master source. Is that correctly understood @ManonGros ?

**Comment by ManonGros** [comment]
Yes you are right, it is now more general than just IH.

What you write is indeed what we should do:a way to define and remove master sources.
I don't know if the API is ready for that though. @marcos-lg ?

**Comment by marcos-lg** [comment]
To disconnect a master source you just need to remove the machine tag

**Comment by MortenHofft** [comment]
And is creating a new master source as simple as creating the machineTag?

**Comment by marcos-lg** [comment]
yeah. For IH it will be synced the next time a sync runs. For datasets and organizations the entity will be synced right after adding the machine tag.

**Comment by marcos-lg** [comment]
So a master source cannot be modified when creating or updating an institution/collection. It's only managed by machine tags.

**Comment by ManonGros** [comment]
What we discussed during the call:

* The place to choose the master source will be in a tab
* Will have a drop down list with source type and show which fields are overwritten depending on type
* Once a type is selected, the user will enter the identifier of the source (dataset UUID or DOI/ IH identifier)
* The master source of the record should be very visible (also in message of suggestion interface).

**Comment by MortenHofft** [comment]
The APIs have changed. MachineTags are no longer used to manage this. Instead a new endpoint has been introduced. See https://github.com/gbif/registry/issues/399#issuecomment-998570630
