### ISSUE TITLE
Show which fields are controlled by the master source

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#430]
There is now an API to show which fields are controlled by the given master source. It would be useful for the users to know which fields would be overwritten on the next sync. Or possibly even disable them in the interface.

http://api.gbif-dev.org/v1/grscicoll/institution/sourceableFields

**Comment by MortenHofft** [comment]
@marcos-lg how is nested fields encoded? E.g. `mailingAddress.city`?

Example from them API
```
[
  {
    "fieldName": "name",
    "sources": [
      {
        "masterSource": "GBIF_REGISTRY",
        "overridable": false,
        "sourceableParts": []
      },
      {
        "masterSource": "IH",
        "overridable": false,
        "sourceableParts": []
      }
    ]
  }
]
```

**Comment by marcos-lg** [comment]
At this moment the addresses are controlled as a whole and we don't support the sourceable fields for nested fields.

`sourceableParts` was created for cases like the `identifiers` to be able to say that only some identifiers come from an external source. Since the identifiers aren't locked in the updates in the API we can ignore it in the UI.

**Comment by MortenHofft** [comment]
@ManonGros should the fields that are controlled by the master be disabled or should there simply be a warning?

**Comment by MortenHofft** [comment]
This is now in place for institutions, but not yet for collections. It can be evaluated on dev. E.g. https://registry.gbif-dev.org/institution/c4b0b9e6-41db-41bb-88de-09341e480765

<img width="568" alt="Screenshot 2021-12-13 at 21 32 41" src="https://user-images.githubusercontent.com/6759267/145884361-b7008a1c-63aa-4200-93f7-74c91f252e6f.png">

**Comment by ManonGros** [comment]
This is great, thanks Morten!
My only comment is about the "controlled by the master source" message. We need to make sure people understand what we mean by "master source". But I assume that this is to be handled in a separate issue.
