### ISSUE TITLE
Incorrect error with "Invalid homepage URI"

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry-console#440]
On the GBIF test (UAT) environment I was able to create [a collection](https://registry.gbif-uat.org/collection/d4ec6d3a-95e2-48d2-91eb-3ba480d6e6a7) without a `Homepage`.  However, if I try and make an edit, it says that the Homepage URI is invalid.

![image](https://user-images.githubusercontent.com/237221/148967596-7e43f100-a9ce-4520-8242-51de17d0c669.png)

A user has also reported the same, so perhaps this appears in suggest a change popups or similar too.

> I have tried to add our collections to our institution, and although the Home Page URL is not a required field, if I try to "create" the collection, it gives me the error tha my "homepage could not be verified". How can I fix this?

**Comment by MortenHofft** [comment]
I cannot reproduce this. I can edit yours. And I can create and subsequent edit my own test collection. I believe those error messages is only used when the backend fails. The UI will warn inline before submitting. 
@marcos-lg perhaps you can explain what the cause is?

**Comment by timrobertson100** [comment]
@MortenHofft - I can reproduce this on [my test](https://registry.gbif-uat.org/collection/d4ec6d3a-95e2-48d2-91eb-3ba480d6e6a7) by logging in, clicking edit, adding a space to the homepage, deleting the space, clicking save

**Comment by MortenHofft** [comment]
Thank you. Yes - i just realised as well.
Indeed. The UI sends an empty string. The backend considers an empty string illegal.

**Comment by MortenHofft** [comment]
@marcos-lg perhaps we should change this in both ends. It seems reasonable that the API should be able to handle an empty string in this case. And I can strip empty strings in the UI as well.

**Comment by marcos-lg** [comment]
In the backend we can convert empty strings to null to avoid this case. It would change for all the URI validations in the registry. But in the meanwhile we can strip the empty strings in the UI.

**Comment by MortenHofft** [comment]
I have changed it in the UI and will deploy it shortly. But normally this isn't an issue. I just tried creating an organisation for example with empty strings for latitude. Latitude normally has to be a float, but an empty string is accepted just fine. So it seems to be an issue specifically for URLs.

**Comment by marcos-lg** [comment]
Yeah it's only for URLs because the URL validator doesn't consider the empty strings as valid.

**Comment by MortenHofft** [comment]
The UI now remove empty strings in this case. It is deployed and in prod
