### ISSUE TITLE
update antd from version 3 => 4

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#445]
Antd is currently blocking us from updating other dependencies (e.g. CRA scripts).
The branch reactscripts5 has updating a lot of dependencies including node version. The development build works, but warns that some antd syntax is unsupported, and it fails when building to production.

`Should not import the named export ‘version’ (imported as ‘version’) from default-exporting module (only default export is available soon)`. 
https://github.com/ant-design/ant-design/issues/25566

The prettiest way to solve this is to update antd to version 4.

**Comment by thomasstjerne** [comment]
https://ant.design/docs/react/migration-v4
