### ISSUE TITLE
GRSciColl - cannot save changes for IH-synchronized entry because invalid phone number

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#446]
In this case, I wanted to add additional information to an IH-synchronized entry (https://registry.gbif.org/institution/6478e22f-b3a4-45f9-9cdf-34dbcdc52761) by adding an additional name and some description. But I couldn't save them because the phone number is invalid (but I cannot change the phone number because it comes from IH):
<img width="668" alt="Screenshot 2022-01-17 at 10 29 25" src="https://user-images.githubusercontent.com/7677271/149743993-89ed1e6a-0d2a-4490-ba52-94b9ec490680.png">

**Comment by MortenHofft** [comment]
We can remove phone number validation as well. That is what we normally do. We started out with validation on most fields, and then we have removed them one by one as this situation arose.

**Comment by marcos-lg** [comment]
We don't have any validation for the phone.
