### ISSUE TITLE
Dataset's networks not displayed

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/registry-console#453]
Example dataset https://registry.gbif-uat.org/dataset/63017d76-b065-4ef1-831c-e1bc983e351d/networks
There is one network associated with the dataset. Counter shows 1, but list is empty

**Comment by MortenHofft** [comment]
This bug looks like it was introduced with the update of our component library AntD. It works fine when using a [previous commit](https://github.com/gbif/registry-console/commit/44ea894740c6c884e3185da1c56b3ef72e0df9cd).

**Comment by MortenHofft** [comment]
Apparently the new version of antd fails and die if it gets a null value as current page, even if it is updated to a valid value 2 ms later. But then again, we shouldn't provide invalid values.
