### ISSUE TITLE
GRSciColl - collection - "Active" checkbox looks empty in editing mode although collection active

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#457]
For example, this collection is active: https://registry.gbif.org/collection/fae61122-9357-4e5b-b755-edd7f7a022d1 but when clicking on "edit", the "Active" checkbox doesn't look checked:
<img width="668" alt="Screenshot 2022-02-11 at 15 12 11" src="https://user-images.githubusercontent.com/7677271/153606977-b17da8cc-6c9b-49f5-b9f0-9911d111ea10.png">

I see in this old issue that the screenshot shows the checkbox at checked:
https://github.com/gbif/registry-console/issues/446
Something must have changed since then.

Would it be possible to make the box look checked when the entity is active? it is a little bit confusing otherwise.

**Comment by MortenHofft** [comment]
All forms was recently updated to a newer version of [Antd](https://ant.design/components/checkbox/#header) (our component library) - it probably happened in that process

**Comment by ManonGros** [comment]
Looks like Thomas fixed it by fixing the other issue (I checked on UAT)
