### ISSUE TITLE
GRSciColl - Suggestion to create entry doesn't work

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#460]
We now got two suggestions to create new GRSciColl entries that were empty:

- https://registry.gbif.org/institution/create?suggestionId=173
- https://registry.gbif.org/collection/create?suggestionId=176

I thought this was odd so I tested suggesting creating a new collection and it doesn't work. I added a name, code, country and institution and here is the result of my suggestion: https://registry.gbif-uat.org/collection/create?suggestionId=68 All the information I entered is gone!

**Comment by MortenHofft** [comment]
Well the positive thing is that it isn't lost. It is in the API. 
https://registry-api.gbif-uat.org/grscicoll/collection/changeSuggestion/68

But the UI doesn't show it when you try to see it
