### ISSUE TITLE
GRSciColl - inactive collection shows as active

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#461]
May be relating to this: https://github.com/gbif/registry-console/issues/457

This collection is inactive: https://registry.gbif.org/collection/04ba168f-8e1e-41ce-b60b-3f58d9b2c7fe, the active box is unchecked. Yet it shows as active both on GBIF.org and on the registry.

**Comment by MortenHofft** [comment]
Why do you say it is inactive?

https://registry-api.gbif.org/grscicoll/collection/04ba168f-8e1e-41ce-b60b-3f58d9b2c7fe
the API says it is active. And you say the registry and gbif.org states it as active

**Comment by ManonGros** [comment]
This is what I mean by "inactive":
<img width="667" alt="Screenshot 2022-02-16 at 12 48 35" src="https://user-images.githubusercontent.com/7677271/154258742-05c4727e-6fe8-4e3c-9d64-df8718464d65.png">
Actually, the person I was talking to today, wanted to show it as inactive but I couldn't find a way to do that in the UI, just unchecking the box doesn't work.
