### ISSUE TITLE
UI doesn't allow me to save changes for organisations

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#467]
The save button isn't clickable.
https://registry.gbif.org/organization/abab411b-cce0-4bb2-b808-354dadeb1eee
<img width="810" alt="Screenshot 2022-02-24 at 09 01 33" src="https://user-images.githubusercontent.com/7677271/155482920-d7961c23-8597-4293-8143-37eaf420092f.png">

Plus if I try to edit contacts, I can click save but the changes aren't saved.

**Comment by ManonGros** [comment]
+ Suggestion creation on GRSciColl look empty again: https://registry.gbif.org/collection/create?suggestionId=194 
https://github.com/gbif/registry-console/issues/460

**Comment by timrobertson100** [comment]
@thomasstjerne 

Marie and I diagnosed and the issue is related to the "tag" style entries. Changing "tags" such as removing an address or removing an email in the contacts form does not save.

**Comment by thomasstjerne** [comment]
> * Suggestion creation on GRSciColl look empty again: https://registry.gbif.org/collection/create?suggestionId=194
>   [GRSciColl - Suggestion to create entry doesn't work #460](https://github.com/gbif/registry-console/issues/460)

It looks like only pending suggestion were meant to populate the form for "create" suggestions?  (maybe in order to avoid duplicates)
https://github.com/gbif/registry-console/blob/3a126f55e37dc618238f3b952867d7b369d71d43/src/components/Collection/Details/index.js#L185
I think this makes sense, but maybe some more meaningful feedback like "this was already applied" or similar would be appropriate?

**Comment by thomasstjerne** [comment]
> The save button isn't clickable.
If you do change a value, it should become active

**Comment by thomasstjerne** [comment]
@ManonGros can you test now? (reload browser first)

**Comment by ManonGros** [comment]
@thomasstjerne yes I could delete the tags I needed to delete and save the changes both for the organization and contacts.

**Comment by ManonGros** [comment]
Thanks @thomasstjerne ! I wonder if we could show some message when a creation suggestion has been applied? Instead of showing the empty form?

**Comment by MortenHofft** [comment]
@ManonGros How do you end up on the page with a suggestId for an already created entity? We shouldn't link to that anywhere I would think

**Comment by ManonGros** [comment]
@MortenHofft 
The links I get in the email notifications are the ones that lead me to this: https://registry.gbif.org/institution/create?suggestionId=201
Since I forward those emails to mediators for review, they also have access to those links.

<img width="754" alt="Screenshot 2022-02-24 at 10 38 01" src="https://user-images.githubusercontent.com/7677271/155498556-6b65d0d0-ee0c-48f5-af69-dec11b6ef29e.png">

**Comment by MortenHofft** [comment]
ahhh, that is where the old link lives. Thank you
