### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#47]
I love that you have added breadcrumbs - it makes it much easier to navigate the site.
But, there is something not quite right in the logic (see https://github.com/gbif/registry-console/issues/36)

It is somewhat difficult to read what it does, and that if it also fails might mean that it is too complex.

I'm wondering wether it would be simpler to move the control to the page displaying it.
So that either `Organization/index.js` calls `this.props.setItem(data.organization.title)` instead or even moving it to `Organization/Details/index.js` as a breadcrumb component used there.

I'm thinking that the breadcrumb component need to do an unnecessary amount of logic/url-parsing when the page knows all that is required to display the proper text already.

You might already have tried it and concluded that it was more complex. Just a thought.

If you decide to stick with the current version, you might consider giving the context function setItem a more informative name (it is used to manipulate the breadcrumbs only)

**Comment by luckyluck** [comment]
Removed BreadCrumbs from Layout and put it on each item's list and details pages. Made BreadCrumbs as dummy as possible. Removed Context collaboration from the BreadCrumbs creation process.
