### ISSUE TITLE
GRSciColl - create suggestion shows a blank page

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#471]
I don't know if it is a browser issue but I can't access this page: https://registry.gbif.org/institution/create?suggestionId=209 (I can see the content in the API but it isn't ideal to forward for review)

**Comment by ManonGros** [comment]
@thomasstjerne @MortenHofft

**Comment by MortenHofft** [comment]
Det lader til at være sket i https://github.com/gbif/registry-console/blame/master/src/components/Institution/Details/index.js#L233
