### ISSUE TITLE
Cannot add tag to dataset

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#474]
The issue was originally reported on Heldpesk by one of our Nodes staff who has access to the registry.
They used to be able to add tag to datasets but not any more.
I myself tried to add a tag to a dataset with my admin account and I get the same error message they get: `Validation of [value] failed: must not be null`:
![image](https://user-images.githubusercontent.com/7677271/160786895-f9509447-64ef-401f-81f1-516ba168f26a.png)

**Comment by ManonGros** [comment]
@thomasstjerne @MortenHofft

**Comment by ManonGros** [comment]
thanks @thomasstjerne ! Could you let me know once it is in prod? I would let our user know when she can start adding tags again

**Comment by thomasstjerne** [comment]
It should be in prod by now - also editing of contacts should be functional in a few minutes
