### ISSUE TITLE
Adapt registry UI to changes in the API

### ISSUE THREAD

**Issue by marcos-lg** [gbif/registry-console#498]
The api has changed to handle the vocabulary and concept labels in a different way and the changes aren't backwards compatible. 

The main change is that when we list vocabularies and concepts the response doesn't contain the labels but a link to the labels endpoint instead, e.g.:

```
"labelsLink": "https://api.gbif-dev.org/v1/vocabularies/Pathway/concepts/Vehicles/labels",
"alternativeLabelsLink": "https://api.gbif-dev.org/v1/vocabularies/Pathway/concepts/Vehicles/alternativeLabels",
"hiddenLabelsLink": "https://api.gbif-dev.org/v1/vocabularies/Pathway/concepts/Vehicles/hiddenLabels"
```

In the alternative and hidden labels there is pagination available since there can be a lot of values. Also, in the labels and the alternative labels we can filter by `lang`.

I deployed the branch containing these changes in DEV, therefore the UI doesn't show the labels. The documentation for all the new label endpoints can be found [here](https://htmlpreview.github.io/?https://github.com/gbif/vocabulary/blob/%23117_performance_tables/vocabulary-rest-ws/src/docs/generated-docs/index.html). For each type of labels there are endpoints to add, update, delete, get and list the labels.

**Comment by MortenHofft** [comment]
This sound like it could also have consequences for portal16 and hosted portals that use the vocabularies for e.g. suggests

**Comment by marcos-lg** [comment]
It might have consequences yeah. Although the suggest endpoints haven't changed.

**Comment by MortenHofft** [comment]
GBIF.org use these I can see in network traffic:
https://api.gbif.org/v1/vocabularies/LifeStage/concepts?limit=20&q=a for suggest
and 
https://api.gbif.org/v1/vocabularies/LifeStage/concepts/Adult to display individual filters

**Comment by marcos-lg** [comment]
We should test them in DEV then. These changes are in a separate branch and I won't release and deploy them until the UIs are adapted.

**Comment by MortenHofft** [comment]
Why is the definition still included but the main label removed? And is it really necessary to remove the label if it is the many alternative and hidden labels that is the issue? I ask because it makes it more difficult for consumers that want to use the API.

Might be worth considering if the API change should be supplemented with a new option to include labels for a specific language. If not always include the labels. Not alternative and hidden labels, it makes sense to move those as they are large, but the main label and definition could still be included. 

Example
`https://api.gbif-dev.org/v1/vocabularies/LifeStage/concepts?limit=20&q=a` includes all languages as usual (but not hidden and alternative.
```
{
  "name": "Adult",
  "label": {
    "en": "Adult",
    "es-ES": "Adulto",
    "nl-NL": "Volwassen"
  },
  "definition": {
    "en": "An adult is an organism that has reached sexual maturity"
  },
  "labelsLink": "https://api.gbif-dev.org/v1/vocabularies/LifeStage/concepts/Adult/labels",
  "alternativeLabelsLink": "https://api.gbif-dev.org/v1/vocabularies/LifeStage/concepts/Adult/alternativeLabels",
  "hiddenLabelsLink": "https://api.gbif-dev.org/v1/vocabularies/LifeStage/concepts/Adult/hiddenLabels"
}
```

Option to only include selected languages (e.g. I need english as a fallback when Spanish is not present)
`https://api.gbif-dev.org/v1/vocabularies/LifeStage/concepts?limit=20&q=a&lang=es-ES&lang=en`
```
{
  "name": "Adult",
  "label": {
    "en": "Adult",
    "es-ES": "Adulto"
  },
  "definition": {
    "en": "An adult is an organism that has reached sexual maturity"
  },
  "labelsLink": "https://api.gbif-dev.org/v1/vocabularies/LifeStage/concepts/Adult/labels",
  "alternativeLabelsLink": "https://api.gbif-dev.org/v1/vocabularies/LifeStage/concepts/Adult/alternativeLabels",
  "hiddenLabelsLink": "https://api.gbif-dev.org/v1/vocabularies/LifeStage/concepts/Adult/hiddenLabels"
}
```

**Comment by marcos-lg** [comment]
I implemented the changes and they are in DEV:

- Definitions are a separate entity too: https://api.gbif-dev.org/v1/vocabularies/LifeStage/definition
- Both labels and definitions are returned in the respones but the format is different because they include the key and other audit fields (it works like machine tags, identifiers, etc.)
- I renamed the `/labels` endpoints to `/label` in singular
- you can filter labels and definitions in their endpoints (not in the vocab or concept search) and you can use multiple values: https://api.gbif-dev.org/v1/vocabularies/LifeStage/concepts/Seedling/label?lang=es-ES&lang=en

**Comment by marcos-lg** [comment]
Done
