### ISSUE TITLE
Could GRSciColl mediators add comments to collections and institutions?

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#522]
Right now it seems like only admins can add comments to institutions and collections. Some mediators asked if they could be allowed to add comments as well.
I don't remember if the restriction is at the API level or in the UI. Could someone take a look? thanks!

**Comment by marcos-lg** [comment]
The API looks fine, I just tried so it seems to be a UI thing. I'll fix it in the UI anyway.

**Comment by marcos-lg** [comment]
Fixed

**Comment by EstebanMH-SiB** [comment]
Thank you very much for your help and speed @marcos-lg , is working perfectly now!
