### ISSUE TITLE
It is difficult to evaluate if a location is correct for institutions

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#529]
Because the address is located elsewhere on the site and the base map doesn't have much information, then it is hard to evaluate if a given location is correct.

As an easy first pass to improve this we can add links to google maps and add an overlay with the address (so that it is handy when looking at the map to place the pin)

**Comment by ManonGros** [comment]
If you come here because you followed the link of one of the GRSciColl homepage update suggestion, we made a mistake, you were meant to be directed here: https://github.com/gbif/registry-console/issues/532
