### ISSUE TITLE
UI: dont open site menu on smaller devices

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#53]
We currently expand the menu for the selected item. On smaller devices that means a tablet user will see a popover when arriving. That is annoying for the user. I think it is as simple as not expanding it on smaller devices.

![screen shot 2018-12-17 at 15 33 28](https://user-images.githubusercontent.com/6759267/50093513-2e89e780-0211-11e9-949a-32d3b37c86ce.png)

**Comment by luckyluck** [comment]
Done!

**Comment by MortenHofft** [comment]
Please feel free to close implemented issues
