### ISSUE TITLE
make a button to tag dataset in order to skip occurrenceID check

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#531]
Right now there is a machineTag which allows to skip occurrence ID checking for a given dataset (@muttcg). There is also a way to change the detection threshold.
I don't remember the namespace to use for that. Maybe it could be directly a UI feature?

**Comment by muttcg** [comment]
There are two options, controlled by adding one of the machine tags:

_Permanently skip the identifier's check._
namespace: **pipelines.gbif.org**
name: **id_threshold_percent**
value: **true/false**

_Set the identifier's check threshold as a percentage._
namespace: **pipelines.gbif.org**
name: **id_threshold_percent**
value: **1-99**

**Comment by MortenHofft** [comment]
I must admit it isn't clear to me what those value mean. Will setting threshold to `true` mean that it skips all records or use some default threshold? 
And does 99 mean that it will accept that 99% of the records have changed or does it mean that at least 99% have to be the same?

**Comment by muttcg** [comment]
@MortenHofft 

Skip id check validation for the dataset
namespace: pipelines.gbif.org
name: id_threshold_skip
value: true

Fail the dataset interpretation if amount of new IDs more than 75% (default is configured to 50%)
namespace: pipelines.gbif.org
name: id_threshold_percent
value: 75

PS. I corrected the typo.

**Comment by ManonGros** [comment]
Thanks @MortenHofft!
