### ISSUE TITLE
Update "Crawl with pipelines" button text 

### ISSUE THREAD

**Issue by MattBlissett** [gbif/registry-console#538]
The button should be renamed "Crawl", since it triggers a crawl (download of the data, if the data is updated).  The argument to .../crawl should be removed too, I think it's been removed from the API.

**Comment by MortenHofft** [comment]
The button now says `Crawl` and 
the request is simply `.post(/dataset/${key}/crawl);` instead of `.post(/dataset/${key}/crawl?platform=PIPELINES);`
