### ISSUE TITLE
Allow filtering of deleted datasets

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/registry-console#539]
The registry UI allow for search on deleted datasets (https://registry.gbif.org/dataset/search?type=deleted). However, this by now returns 479 pages over a total of 11,967 results. It would occasionally be very helpful to identify previously deleted datasets, and an active search filter in that sub-selection limited to deleted sets would be helpful for that, so as to not having to go into the backend. 

![image](https://user-images.githubusercontent.com/13435656/197709313-4feabaa3-2ce4-4859-9825-b67ff22d4064.png)

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/registry-console/commit/415fd3dd9d5b8c3a6810296cc0446cec489316ee

**Comment by ahahn-gbif** [comment]
@MortenHofft, even on vpn, using the "deleted" filter on https://registry.gbif.org/organization/search without any additional criteria gets me to an empty page right now (https://registry.gbif.org/organization/search?limit=25&type=deleted). SUE or something else?

**Comment by MortenHofft** [comment]
I haden't relised that the feature had been added to search deleted organizations as well. Deploying fix now
