### ISSUE TITLE
translating missing fields

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#54]
https://gbif-registry-demo.netlify.com/organization/8603f538-d548-4c91-a169-b95f2bb5c1e4

Shows a half translated country even when there isn't any.

![screen shot 2018-12-17 at 15 35 09](https://user-images.githubusercontent.com/6759267/50093706-b96ae200-0211-11e9-83c4-a9b9b854a0a4.png)

**Comment by luckyluck** [comment]
Removed default translations for such fields (Organization presentation page and Node presentation page).

**Comment by MortenHofft** [comment]
@luckyluck Can this issue be closed?
