### ISSUE TITLE
Allow a user with namespace rights to create new machine tags, and a shortcut for privateSector.gbif.org

### ISSUE THREAD

**Issue by MattBlissett** [gbif/registry-console#547]
If a user has namespace_rights over a machine tag namespace, they can create and delete new machine tags in that namespace.  The UI shows the ability to delete them, but not to create them.

Additionally, it would be very useful if a common machine tag block for `{"namespace": "privateSector.gbif.org", "name": "sector", "value": ""}` could be added *for organizations*, especially if the value was a drop-down list with these values:

```
       namespace        │  name  │      value
────────────────────────┼────────┼──────────────────
 privateSector.gbif.org │ sector │ Agriculture
 privateSector.gbif.org │ sector │ Consulting
 privateSector.gbif.org │ sector │ Consumer Staples
 privateSector.gbif.org │ sector │ Energy
 privateSector.gbif.org │ sector │ Engineering
 privateSector.gbif.org │ sector │ Health Care
 privateSector.gbif.org │ sector │ Industrials
 privateSector.gbif.org │ sector │ Materials
 privateSector.gbif.org │ sector │ Mining
 privateSector.gbif.org │ sector │ Utilities
```

Required for https://github.com/gbif/doc-private-sector-data-publishing/pull/26 and/or https://github.com/gbif/doc-private-sector-data-publishing/issues/25

Example organization: https://registry.gbif.org/organization/ca11748e-a30a-4252-930f-bdb017e942c5/machineTag

**Comment by MortenHofft** [comment]
The UI screenshot you sent yesterday Matt includes a create button. doesn't it work?

**Comment by MattBlissett** [comment]
Actually it does, I must have mistyped the namespace when I tested.

Then all that's required is the "Shortcuts for frequently used machine tags" to be added to organizations, with the privateSector.gbif.org tag as above.

**Comment by MortenHofft** [comment]
@MattBlissett I've allowed multiple sectors to be attached.
