### ISSUE TITLE
GRSciColl - can't set up number of specimens above 100 million

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#555]
It looks like I can't add an estimated number of specimens above 100,000,000 for institutions on GRSciColl.
The Smithsonian has "148 million specimens and artifacts" but I don't seem to be able to update their entry: https://registry.gbif.org/institution/586ee56e-b0fe-4dff-b7f9-aeb104f3308a

**Comment by MortenHofft** [comment]
The number was set to maximum 100,000,000 records. I think that was done to avoid accidental high numbers.
I've changed it to 1 billion now.
