### ISSUE TITLE
Missing locale data for locale: "undefined". 

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#56]
`index.js:1452 [React Intl] Missing locale data for locale: "undefined". Using default locale: "en" as fallback.`

If no locale selected it should use english - no need to throw errors.

**Comment by luckyluck** [comment]
It looks like it's a default react-intl behavior to throw a warning to the console in the dev mode. As I checked, there is no log in the console in the prod mode.

**Comment by MortenHofft** [comment]
Isn't it as simple as setting english as default locale if non is seleced and none is in local storage?

**Comment by luckyluck** [comment]
EN is the default locale in the case of empty storage or absence of the key for the selected locale. Warnings in the console are for the developer and will not be shown in the production to the user.
