### ISSUE TITLE
vocabulary values not possible to select in UI

### ISSUE THREAD

**Issue by mnhn-paul** [gbif/registry-console#568]
I wanted to edit some of our entries for Luxembourg but noticed that it was not possible to select values for certain fields that refer to vocabularies eg. Discipline & [InstitutionalGovernance](https://registry.gbif.org/vocabulary/InstitutionalGovernance)

![image](https://github.com/gbif/registry-console/assets/26623703/3daa1d0c-4467-440a-99ea-796ded42df10)

**Comment by MortenHofft** [comment]
Thanks for reporting it. @marcos-lg and @ManonGros looks like a backend or data management issue to me.
InstitutionalGovernance vocab is missing as far as I can see from the latest release

**Comment by marcos-lg** [comment]
Just released the InstitutionalGovernance vocab
