### ISSUE TITLE
contact form

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#57]
The contact form shows as requiring userid, phone, email and position. that sounds wrong. Could you please check that is the case in the API?

**Comment by luckyluck** [comment]
Actually, I took this from current form https://registry-demo.gbif-dev.org/web/#/organization/8603f538-d548-4c91-a169-b95f2bb5c1e4/contact. Could you please tell me where I can check the list of required fields?

**Comment by MortenHofft** [comment]
those fields aren't required in the existing form either. It is that discussion we had in https://github.com/gbif/registry-console/issues/9

I just created a contact with first name only. apparently there is no required fields

**Comment by luckyluck** [comment]
But does it make sense to create a contact without any data? As all fields are optional it's possible to do.

**Comment by MortenHofft** [comment]
i agree - but it doesn't make sense to have one where name isn't required but a homepage is.
Perhaps we should select some (even though it is front end only)

**Comment by luckyluck** [comment]
sure. anyway, I'll remove required options from all fields.

**Comment by MortenHofft** [comment]
At this point I think we might just have to go with none. Contacts aren't always persons - sometimes they are institutions (no first and last name). Or alternatively - first name OR and organisation name. @timrobertson100 and @asturcon are there any reason we do not have any validation on contacts? I assume it is because the data we already have do not adhere by it?

**Comment by luckyluck** [comment]
Removed all require marks.
