### ISSUE TITLE
Support hyperlinks in the Definitions, Editorial Notes and External Definitions

### ISSUE THREAD

**Issue by CecSve** [gbif/registry-console#581]
We should consider supporting hyperlinks (and potentially more text formatting options) in the ~`Descriptions`~ `Definitions`, `Editorial Notes` and `External Definitions` fields. For example in the GeoTime vocabulary, it would be nice to be able to link to the Paleo Data Work Group page and the International Commission of Stratigraphy.

**Comment by MortenHofft** [comment]
I do not see anything called `Descriptions` - do you mean `definitions`?

For input: I notice that they are all just single input fields. That doesn't seem ideal. Would simply changing that to a multiline text box help? 
If we really want a rich text editor, then it is a bit more work, and we would probably want to do sanitisation in the backend.

For presentation: would it help simply respecting new lines and make links clickable?

**Comment by CecSve** [comment]
> I do not see anything called `Descriptions` - do you mean `definitions`?
> 
> For input: I notice that they are all just single input fields. That doesn't seem ideal. Would simply changing that to a multiline text box help? If we really want a rich text editor, then it is a bit more work, and we would probably want to do sanitisation in the backend.
> 
> For presentation: would it be sufficient to simply respect new lines and make links clickable? Or do we need options to create and present bullet lists, headlines, italics, bold, tables etc.
> 
> Example record with link and newlines: https://registry.gbif-uat.org/vocabulary/CollectionContentType/concept/Recordings
> 
> UPDATE: I notice that on creation it is single line, but when editing it is a proper text box

Sorry, you are right. I have changed the terms now. Yes, a multiline text box would be great, thanks! We really need those hyperlinks to be supported since we need to be able to point to sources where we have been given permission to use their data to construct the vocabularies. 

We would not need more than new lines and clickable links for now.
