### ISSUE TITLE
links on registry.gbif.org landing page are not working properly

### ISSUE THREAD

**Issue by mnhn-paul** [gbif/registry-console#583]
I noticed not all the URLs that are mentioned as examples on the registry landing page registry.gbif.org are working.
These 3 lead to a 404 page:
* Collections: entities describing mainly museum collections, e.g. [Hacettepe University Biodiversity Advanced Research Center Genbank](https://registry.gbif.org/collection/9f351d9d-2df2-4d88-9358-ff59abe245aa)
* Institutions: entities responsible for collections , e.g. [Hacettepe University Biodiversity Advanced Research Center (BIOSPHERE)](https://registry.gbif.org/institution/87095cd2-ed2a-4d4b-a97d-885e7e6bedf9)
* GRSciColl Staff: people associated with institutions, e.g. [Selim Sualp Çağlar](https://registry.gbif.org/person/d4591800-8b5a-44f8-a7a8-e3ea1a59365c)

**Comment by MortenHofft** [comment]
Thanks. That text feels misplaced in many ways. And a missed opportunity for communication. I just wrote that as a placeholder, and it was never replaced. I will update it and raise the opportunity. Thanks again
