### ISSUE TITLE
Presentation layout similarity to form

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#59]
The idea with having a presentation view instead of simply a disabled form is that it reads better. So I then created a presentation component that were to resemble the form in layout. The idea being that the layout would remain largely the same:

* similar spacing.
* when the form is horizontal, so is the presenation.
* same alignment of text. same text size etc.

The form layout has since changed some. Could you please revisit the presentation layout and components to make sure the align again (once you have found a format for the forms that you like)

![editvspresentation](https://user-images.githubusercontent.com/6759267/50095600-2f714800-0216-11e9-9358-c94f33490026.png)

**Comment by luckyluck** [comment]
I refactored contact form as is shown here. Also, I improved a bit other forms to make them horizontal and vertical at the same situations. Most probably, I should refactor presentational component to have a more form-like view.

**Comment by luckyluck** [comment]
@MattBlissett, could you please check changes for Contact form in the pull request. If the realization is good, I'll provide the same changes for all presentational views.
