### ISSUE TITLE
GRSciColl - add checkbox to select primary identifier

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#594]
Now that the back end has been implemented (https://github.com/gbif/registry/issues/625), I would like to make it possible for editors to choose a primary identifier. Maybe with a checkbox in the identifier window like we have for contacts? (see below)

What we currently have for contacts:

![Image](https://github.com/user-attachments/assets/f639387e-5b6b-41bc-aadc-c3e9f8fe64d0)

Where I imagine the checkbox would be for identifiers:

![Image](https://github.com/user-attachments/assets/07c5c545-0101-4050-ba3b-4b1863e236a7)

See also this issue on displaying identifiers in the GRSciColl website: https://github.com/gbif/hp-grscicoll/issues/158

**Comment by dagendresen** [comment]
We would also need functionality to edit existing institution identifiers to set the primary checkbox (now it only works when adding a new identifier).
