### ISSUE TITLE
Installation sync button logic

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#6]
Installations have a `synchronization` button.

It should only show if `type` equals `digir`,  `tapir`, `digir-manis` or `biocase`. I do not remember the proper ENUM values/spellings for these. But it should be apparent from the API.

**Comment by MattBlissett** [comment]
https://api.gbif.org/v1/enumeration/basic/InstallationType

```
[
"IPT_INSTALLATION",
"DIGIR_INSTALLATION",
"TAPIR_INSTALLATION",
"BIOCASE_INSTALLATION",
"HTTP_INSTALLATION",
"SYMBIOTA_INSTALLATION"
]
```

So it's actually `DIGIR_INSTALLATION`, `TAPIR_INSTALLATION` and `BIOCASE_INSTALLATION` that can be synchronized.

**Comment by luckyluck** [comment]
Added API for synchronization. Also, added installation types restrictions. Could you please clarify who can invoke synchronization and how to check a status of synchronization?

**Comment by MortenHofft** [comment]
who can do it. REGISTRY_ADMIN and (I'm guessing) EDITORS with the installation in scope. 
the installation can be owned by an organization and that organization is endorsed by a node. If either the org or the node is in scope, then the registry_editor can sync.

**Comment by MortenHofft** [comment]
> how to check a status of synchronization

I'm afraid I do not know. The current registry do not do such a test, so let us ignore that for now.
When you trigger the synchronization and get a success back from the API, then simply show a notification telling the user that the sync is in progress.

**Comment by MortenHofft** [comment]
how to sync: simply do a post to `/installation/[key]/synchronize`

**Comment by luckyluck** [comment]
@MortenHofft , I improved permission check for Installations. I tried to sync an installation or crawl a dataset but got a 403 response. Is it because of localhost or is there any other reason?

**Comment by MortenHofft** [comment]
Localhost shouldn't matter. It should work the same as the demo site, where I believe it works. Odd. I can try later

**Comment by MortenHofft** [comment]
I just tested. it works if you are an admin, not with editor role.

**Comment by MortenHofft** [comment]
See https://github.com/gbif/registry/issues/85
I think the API only accepts basic Auth. Just leave it be as it is. It should be fixed in the APIs.
