### ISSUE TITLE
wrong menu item highlighted

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#63]
when navigating to an organization via search, the search menu item remains active. Unless you do a refresh. I'm not sure what to highlight. probably nothing as it isn't in the menu?

**Comment by luckyluck** [comment]
@MortenHofft , it's strange, but looks like it works for me. Could you please check it again with changes from pull request?

**Comment by MortenHofft** [comment]
still the same when using https://gbif-registry-demo.netlify.com/organization/search

**Comment by luckyluck** [comment]
@MortenHofft , could you please clarify the case when I should check the menu? It looks like you mean the case when a user is inside an item and nothing is highlighted in the main menu. But in that case, it's impossible to indicate the right item type for the main menu due to similar URLs.
