### ISSUE TITLE
list layout

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#64]
I find that the lists (contacts/identifiers etc) is a bit messy. Could we make them more like the tables and make the name open details as well (instead of having to click details). 

![screen shot 2018-12-18 at 10 48 15](https://user-images.githubusercontent.com/6759267/50145708-73b22600-02b2-11e9-838f-5da7aeda6d6b.png)

Perhaps adding a popover with info about the type (when there are any. e.g. "Comments allow administrators to leave context about communications with publishers etc.")

**Comment by luckyluck** [comment]
First name, last name, and organization could be skipped during the creation of contact. In that case, it would be impossible to open the contact if we move the opening of details from a separate button to a title.

**Comment by luckyluck** [comment]
I added several improvements to the lists. @MortenHofft , Could you please check them?

**Comment by MortenHofft** [comment]
I still find that it would be intuitive to be able to open list details by clicking the "header". `Bruno Danis` in above example. Keeping the "Details" link, but also supporting the header click.

Are there any reasons not to?
