### ISSUE TITLE
UI: context revisited

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#65]
I'm still not too happy with how the items are presented. I looked at the original specs that Tim provided and the idea presented there seems reasonable. I think we should go with a variant of that.

**current UI**
![screen shot 2018-12-18 at 12 08 31](https://user-images.githubusercontent.com/6759267/50150301-d3fa9500-02bd-11e9-9cef-b39dc54deb0c.png)

**suggested variant on the specs**
and yes!, the content isn't the correct one 
![details2 copy](https://user-images.githubusercontent.com/6759267/50150310-e07eed80-02bd-11e9-8818-9cb905fc1f30.png)

Perhaps page actions could then go next to the h1. e.g. `Crawl`, `Sync`. Perhaps even `Create new` on plain search

**Comment by luckyluck** [comment]
I did it:
- created new component ItemHeader
- moved "Create new" buttons to this component
- moved "Sync" and "Crawl" buttons to this component
- other changes connected to the first three points

Changes located in a branch, I'll create new pull request soon.

**Comment by MortenHofft** [comment]
@luckyluck - great - when doing so and you believe this issue is implemented and no longer relevant, then please close it.

**Comment by MortenHofft** [comment]
Not all headers are aligned. 
![screen shot 2018-12-21 at 10 38 02](https://user-images.githubusercontent.com/6759267/50335732-86279c00-050c-11e9-95a0-cafe3add3a28.png)
