### ISSUE TITLE
Document title from table component

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#67]
https://github.com/gbif/registry-console/blob/d3f5aeead9d0d8cb4b06d09ab7e6a81aca5013f6/src/components/DataTable.js#L40

Just a thought, but perhaps controlling document title from a component that can be reused isn't ideal? Currently it isn't an issue, but I would think controlling document titles would be more tied to the route or route specific component.

**Comment by luckyluck** [comment]
I did it when I added an ItemHeader component. You can check it in a current pull request.
