### ISSUE TITLE
organization subtype popup

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#7]
I'm not sure what the state of the organisation subtypes are in. But I have some comments for how they work in the pull request in the organisation branch.

* Not all users should have access to editing and creating. Please see https://github.com/gbif/registry-console/issues/1
* I think it is unfortunate to close the modal on a whimsical user click outside. Since data will be lost that should be a difficult action. please only close modals with forms if the user clicks a cancel.
* There is no feedback to the user when the action is rejected from the server.
* endpoint type is a required field.
* endpoint urls should be validated as such
* It isn't possible to see contact info if you are not an editor

**Comment by luckyluck** [comment]
@MortenHofft , could you please check improvements in the latest pull request?
