### ISSUE TITLE
Hidding twice?

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#73]
https://github.com/gbif/registry-console/blob/048b4793961f970d1aea1acf5143a56d26aa5004/src/components/Layout/UserMenu/index.js#L111

This looks like hidding twice. Is there a need for the `this.state.visible && ...` the modal has its own visible prop
```
{ this.state.visible && <Modal
          title={<FormattedMessage id="login" defaultMessage="Login"/>}
          visible={this.state.visible}
          onOk={this.handleLogin}
          onCancel={this.handleCancel}
          footer={null}
        >
```

**Comment by luckyluck** [comment]
Actually, no. I just removed the useless part.
