### ISSUE TITLE
Popups always shows as edit

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#79]
When not logged in and clicking view on a subtype I see this:

![screen shot 2018-12-20 at 10 20 26](https://user-images.githubusercontent.com/6759267/50276016-2617f380-0441-11e9-8c8f-746fbaa21ec1.png)

The title shouldn't be edit (as I'm not editing nor am I allowed to)
The edit button shouldn't show (not as disabled either)
There is nothing to cancel

I would think it read:
Title: `Contact: Mari Steinart` or `Contact detailds` or similar
Button: Close or OK

**Comment by luckyluck** [comment]
I decided to go with `Contact detailds`.
