### ISSUE TITLE
subtype lists

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#8]
I'm wondering what actions to display in the lists. Currently you cannot see contact details for example-

Perhaps there should always be the action `Details`.

The popup will then always be there for all types. The popup will then show the presentation view and if you are an editor, the option to delete or toggle to editing. Just like we have for the base type. Perhaps the edit action could stay in the list simply as a shortcut. The double popup might not work when seeing it in action though.

That at least is what I can think of of the top of my head.

**Comment by luckyluck** [comment]
Added popup for preview.
