### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#81]
https://github.com/gbif/registry-console/blob/083e33d0fae501e81377595c273f3c2465ad7a95/src/components/Dataset/index.js#L61

Aren't we missing the hosting org endorsing node? - please see https://github.com/gbif/registry-console/issues/72

**Comment by luckyluck** [comment]
@MortenHofft, as we discussed, I added a TODO about that. If it's all by now, could you please close the issue?
