### ISSUE TITLE
what are the possible values on collection/institutions/persons

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#83]
since there is no former implementation to refer to we need a list of possible fields and requirements. @asturcon could you please list them?

**Comment by asturcon** [comment]
These are the DB constraints, names are almost the same as the ones returned in the JSON:

Institution:
         key uuid NOT NULL PRIMARY KEY,
	code varchar NOT NULL CHECK (assert_min_length(code, 1)),
	name varchar NOT NULL CHECK (assert_min_length(name, 1)),
	description text CHECK (assert_min_length(description, 10)),
	type enum_institution_type,
	active bool,
	homepage varchar CHECK (assert_is_http(homepage)),
	catalog_url varchar CHECK (assert_is_http(catalog_url)),
	api_url varchar CHECK (assert_is_http(api_url)),
	institutional_governance enum_institution_governance,
	discipline varchar[],
	latitude NUMERIC(8,6) CHECK (latitude >= -90 AND latitude <= 90),
	longitude NUMERIC(9,6) CHECK (longitude >= -180 AND longitude <= 180),
	mailing_address_key int4 REFERENCES address(key) ON DELETE CASCADE,
	address_key int4 REFERENCES address(key) ON DELETE CASCADE,
	additional_names text[],
	founding_date date,
	geographic_description text CHECK (assert_min_length(geographic_description, 1)),
	taxonomic_description text CHECK (assert_min_length(taxonomic_description, 1)),
	number_specimens int4,
	index_herbariorum_record bool,
	logo_url varchar CHECK (assert_is_http(logo_url)),
	cites_permit_number varchar CHECK (assert_min_length(cites_permit_number, 1)),
	created_by varchar NOT NULL CHECK (assert_min_length(created_by, 3)),
	modified_by varchar NOT NULL CHECK (assert_min_length(modified_by, 3)),
	created timestamptz NOT NULL DEFAULT now(),
	modified timestamptz NOT NULL DEFAULT now(),
	deleted timestamptz NULL

Collection:
         key uuid NOT NULL PRIMARY KEY,
	code varchar NOT NULL CHECK (assert_min_length(code, 1)),
	name varchar NOT NULL CHECK (assert_min_length(name, 1)),
	description text CHECK (assert_min_length(description, 5)),
	content_type varchar[],
	active bool,
	personal_collection bool DEFAULT false,
	doi varchar CHECK (assert_min_length(doi, 1)),
	homepage varchar CHECK (assert_is_http(homepage)),
	catalog_url varchar CHECK (assert_is_http(catalog_url)),
	api_url varchar CHECK (assert_is_http(api_url)),
	preservation_type varchar[],
	accession_status enum_collection_accession_status,
	institution_key uuid REFERENCES institution(key),
	mailing_address_key int4 REFERENCES address(key) ON DELETE CASCADE,
	address_key int4 REFERENCES address(key) ON DELETE CASCADE,
	created_by varchar NOT NULL CHECK (assert_min_length(created_by, 3)),
	modified_by varchar NOT NULL CHECK (assert_min_length(modified_by, 3)),
	created timestamptz NOT NULL DEFAULT now(),
	modified timestamptz NOT NULL DEFAULT now(),
	deleted timestamptz NULL

Person:
        key uuid NOT NULL PRIMARY KEY,
	first_name varchar NOT NULL CHECK (assert_min_length(first_name, 1)),
	last_name varchar CHECK (assert_min_length(last_name, 1)),
	position varchar CHECK (assert_min_length(position, 1)),
	area_responsibility varchar CHECK (assert_min_length(area_responsibility, 1)),
	research_pursuits text CHECK (assert_min_length(research_pursuits, 1)),
	phone varchar CHECK (assert_min_length(phone, 5)),
	fax varchar CHECK (assert_min_length(fax, 5)),
	email varchar CHECK (assert_min_length(email, 5)),
	mailing_address_key int4 REFERENCES address(key) ON DELETE CASCADE,
	primary_institution_key uuid REFERENCES institution(key),
	primary_collection_key uuid REFERENCES collection(key),
	created_by varchar NOT NULL CHECK (assert_min_length(created_by, 3)),
	modified_by varchar NOT NULL CHECK (assert_min_length(modified_by, 3)),
	created timestamptz NOT NULL DEFAULT now(),
	modified timestamptz NOT NULL DEFAULT now(),
	deleted timestamptz NULL

And these are for the addresses which are included in the entities:
Address:
	key serial NOT NULL PRIMARY KEY,
	address text CHECK (assert_min_length(address, 1)),
	city varchar CHECK (assert_min_length(city, 1)),
	province varchar CHECK (assert_min_length(province, 1)),
	postal_code varchar CHECK (assert_min_length(postal_code, 1)),
	country varchar CHECK (length(country) = 2),

**Comment by luckyluck** [comment]
@MortenHofft, I improved items forms. But there is а couple of things that confuse me. 

First, I can't "save" any of item because of 404 exceptions on every PUT request. Nevertheless, after page reload I see that item was updated.
Second, I do not know what to do with `mailing_address_key` and `address_key` fields. Could you please clarify the type and/or format of the fields?

All in all, I see only these two problems to solve to close and issue.

**Comment by MortenHofft** [comment]
> First, I can't "save" any of item because of 404 exceptions on every PUT request. Nevertheless, after page reload I see that item was updated.
Second, I do not know what to do with mailing_address_key and address_key fields. Could you please clarify the type and/or format of the fields?

I'm afraid I do not know. @asturcon could you please clarify this? 

i suspect the 404 is a mistake and that mailing_address_key are simply foreign keys that are resolved in the API, so they appear as `address, city, province, postalCode, country` in the API.

**Comment by asturcon** [comment]
The addresses can be sent embedded in the collection object, as a json object - like they are returned in a GET request. 

The 404 I will have to check it when I'm at the office next week.

**Comment by MortenHofft** [comment]
> The addresses can be sent embedded in the collection object, as a json object - like they are returned in a GET request.

I wouldn't change it @asturcon . I think it makes sense to have the addresses like they are in the API. The question was simply how to understand it. And unless I misread it is simply how you model it in the database, but in the API it appears as if it was part of the institution/collection/person table.

**Comment by asturcon** [comment]
Yeah, I think you misread it, I'm not gonna change it.

**Comment by luckyluck** [comment]
@MortenHofft, I'm trying to add a new contact to Institution or Collection sending POST request with body `{"key":"0e339a21-f8a7-46b2-b0e2-0c2c29848837"}` and every time I have an exception 
`Can not deserialize instance of java.util.UUID out of START_OBJECT token
 at [Source: HttpInputOverHTTP@77e46c5c[c=46,s=STREAM]; line: 1, column: 1]`
I just can't understand from this exception what am I doing wrong. Would youmind to clarify it for me?

**Comment by asturcon** [comment]
I think you have to send just the UUID in the body:
"0e339a21-f8a7-46b2-b0e2-0c2c29848837"

**Comment by asturcon** [comment]
When you sent the single value, was it surrounded by curly braces? I think it should be without curly braces

**Comment by luckyluck** [comment]
Actually, no. As I can see from the request, the value was sent without curly braces. Here are dumps from Chrome:
**CURL**
`curl "https://registry-demo.gbif-dev.org/grbio/collection/b8b22fe6-c4d1-48e6-b382-2465dff6ee3c/contact" -H "Accept: application/json, text/plain, */*" -H "Referer: http://localhost:3000/grbio/collection/b8b22fe6-c4d1-48e6-b382-2465dff6ee3c/contact" -H "Origin: http://localhost:3000" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36" -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NDcxMTU5NTksImlhdCI6MTU0NjUxMTE1OSwiaXNzIjoiR0JJRi1SRUdJU1RSWSIsInVzZXJOYW1lIjoiYWRtaW4ifQ.v7NOyDRww0_47F_-kWfAv9UborJ71PFMerDXZKwfAqo" -H "DNT: 1" -H "Content-Type: application/x-www-form-urlencoded" --data "0e339a21-f8a7-46b2-b0e2-0c2c29848837" --compressed`
**CMD**
`Invoke-WebRequest -Uri "https://registry-demo.gbif-dev.org/grbio/collection/b8b22fe6-c4d1-48e6-b382-2465dff6ee3c/contact" -Method "POST" -Headers @{"Accept"="application/json, text/plain, */*"; "Referer"="http://localhost:3000/grbio/collection/b8b22fe6-c4d1-48e6-b382-2465dff6ee3c/contact"; "Origin"="http://localhost:3000"; "User-Agent"="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36"; "Authorization"="Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NDcxMTU5NTksImlhdCI6MTU0NjUxMTE1OSwiaXNzIjoiR0JJRi1SRUdJU1RSWSIsInVzZXJOYW1lIjoiYWRtaW4ifQ.v7NOyDRww0_47F_-kWfAv9UborJ71PFMerDXZKwfAqo"; "DNT"="1"} -ContentType "application/x-www-form-urlencoded" -Body "0e339a21-f8a7-46b2-b0e2-0c2c29848837"`
**FETCH**
`fetch("https://registry-demo.gbif-dev.org/grbio/collection/b8b22fe6-c4d1-48e6-b382-2465dff6ee3c/contact", {"credentials":"include","headers":{"accept":"application/json, text/plain, */*","authorization":"Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NDcxMTU5NTksImlhdCI6MTU0NjUxMTE1OSwiaXNzIjoiR0JJRi1SRUdJU1RSWSIsInVzZXJOYW1lIjoiYWRtaW4ifQ.v7NOyDRww0_47F_-kWfAv9UborJ71PFMerDXZKwfAqo","content-type":"application/x-www-form-urlencoded"},"referrer":"http://localhost:3000/grbio/collection/b8b22fe6-c4d1-48e6-b382-2465dff6ee3c/contact","referrerPolicy":"no-referrer-when-downgrade","body":"0e339a21-f8a7-46b2-b0e2-0c2c29848837","method":"POST","mode":"cors"});`

**Comment by asturcon** [comment]
I think the content type is wrong, it should be json. Anyway, I'll check it next week when I'm at the office.

**Comment by asturcon** [comment]
I was doing some tests and this CURL request works for me:
`curl -i -X POST http://api.gbif-dev.org/v1/grbio/institution/5e9b1c0b-67ad-4d74-90f6-e160a01c016f/contact -H 'Authorization: Basic bWxvcGV6ZzptbG9wZXo=' -H 'Content-Type: application/json' --data '"aa841451-b23d-4a5c-80ab-64dd4d82f08f"'`

I've also tested it using Postman and sending this in the body as `application/json`:
`"aa841451-b23d-4a5c-80ab-64dd4d82f08f"`

Can you try to do something like that?

About the 404 response in PUT requests, it looks like it's a mistake. I'll let you know when it's fixed.

**Comment by MortenHofft** [comment]
`text/plain` seems a better content type for this then. Unless we use `application/json` for sending text other places in the registry. In that case we can discuss if consistency is more important.

**Comment by asturcon** [comment]
The add contact endpoint has been changed to accept text/plain and the 404 response in PUT requests have been fixed. 

Both changes are available in DEV and DEMO.

**Comment by luckyluck** [comment]
@MortenHofft, would you mind to tell me if we can close this issue? as for me, we have done everything already.
