### ISSUE TITLE
missing translations

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#85]
there are still keys that are missing translations. Please add them to the english translation file.

**Comment by MortenHofft** [comment]
there is still translation errors. E.g. `[React Intl] Cannot format message: "submenu.synchronizationHistory", using message id as fallback.`

**Comment by luckyluck** [comment]
> there is still translation errors. E.g. `[React Intl] Cannot format message: "submenu.synchronizationHistory", using message id as fallback.`

There is such a key in the localization file. It fails only on page load/reloads. If you open another page first time and navigate on the page where you saw an exception via route link, the exception will not appear again.
