### ISSUE TITLE
Provide map to set latitude and longitude

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#89]
Currently you have to set lat lng by typing the coordinates. The way that is done is probably using Google maps and copy pasting the coordinates (and try not to switch them around). It would be a useful improvement to be able to set the coordinates from a map within the app.

**Comment by luckyluck** [comment]
@MortenHofft, I need an API key for Google maps to finish this task - without key the map works only in dev mode and displays watermarks everywhere, 
Also, is it possible to store key as an environment variable on the server or it's okay to have key directly in the code with Google API's restrictions only?

**Comment by MattBlissett** [comment]
We could use our own map tiles, the URLs are:

```
https://tile.gbif.org/3857/omt/Z/X/Y@2x.png?style=osm-bright
```

Or `osm-bright-en`, `osm-bright-ru` etc for translated place names.

**Comment by luckyluck** [comment]
@MattBlissett, perhaps, I cannot make such decisions. Would it be really better than Google maps? I tried to open the link but saw only 400 error. Probably, I did something wrong. @MortenHofft, could you please clarify this moment?

**Comment by MortenHofft** [comment]
No Google maps please. OSM tiles and leaflet are probably the best fit for this as we do not need a global map (Mercator only) and leaflet has a smaller footprint than OpenLayers. We can use our own tiles, but I would be happy using standard OSM ones.

Above link works fine, but you need to specify the tile in case: https://tile.gbif.org/3857/omt/0/0/0@2x.png?style=osm-bright

**Comment by luckyluck** [comment]
I replaced Google Maps with Leaflet (OpenStreet) and here it can be checked:
- [created organization](https://map--gbif-registry-demo.netlify.com/organization/f87854d3-c6f9-42ee-b2db-fc0bffd5c7e1)
- [new organization](https://map--gbif-registry-demo.netlify.com/organization/create)

**Comment by MortenHofft** [comment]
bug:
deleting a coordinate will make the app crash.

ui - smaller sizes looks odd to me with the header in slightly off center:
![screen shot 2019-02-21 at 12 52 23](https://user-images.githubusercontent.com/6759267/53167271-c58b6b00-35d7-11e9-956b-1132779409af.png)

I suggest making it same width as the longitude input field and removing the header. Possible adding the (?) explanation in the corner of the map

**Comment by MortenHofft** [comment]
Panning the map will allow the user to set longitudes outside the allowed -180<->180 range

**Comment by MortenHofft** [comment]
bug: I cannot delete coordinates without the app crashing

**Comment by luckyluck** [comment]
> bug:
> deleting a coordinate will make the app crash.
> 
> ui - smaller sizes looks odd to me with the header in slightly off center:
> ![screen shot 2019-02-21 at 12 52 23](https://user-images.githubusercontent.com/6759267/53167271-c58b6b00-35d7-11e9-956b-1132779409af.png)
> 
> I suggest making it same width as the longitude input field and removing the header. Possible adding the (?) explanation in the corner of the map

@MortenHofft, is it really a good idea to set map width the same as fields? In my opinion, the map will be too small on the modal popup. I would suggest to get rid of the header and add a tooltip in the corner of the map, but keep the width of the map as it is now.

**Comment by luckyluck** [comment]
If we keep the width, I'll look like this:
![06879a6653](https://user-images.githubusercontent.com/2361566/53175595-7dd80400-3616-11e9-8df1-c559ab6ffb73.png)
![a40808f6d1](https://user-images.githubusercontent.com/2361566/53175596-7dd80400-3616-11e9-961e-f5542fe82f86.png)
