### ISSUE TITLE
multi field values indicating by *

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#9]
https://github.com/gbif/registry-console/pull/3/files#diff-a34682e80f8c4f8e29f8eebf2898358cR102

I know that is what the current registry states, but I'm not a fan of that. Could we please try to come up with something less misleading. It looks an awful lot like required fields. A comment below the field telling the user that they can add more e.g. Perhaps an antd variation of https://codepen.io/broneks/pen/objeqq

![screen shot 2018-12-10 at 16 59 09](https://user-images.githubusercontent.com/6759267/49744396-f2003e00-fc9c-11e8-8915-6665b9ee08a1.png)

**Comment by luckyluck** [comment]
Morten, I've done such changes. Could you please check Organization, Contact and Tag form.
