### ISSUE TITLE
error messages on failed organization load

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#91]
accesssing an organization where the endpoint fails simply shows a loader. No error message provided to the user. not as notification and not on page.

![screen shot 2018-12-21 at 10 07 06](https://user-images.githubusercontent.com/6759267/50334476-b836ff00-0508-11e9-9e0d-1c18464db1f5.png)

**Comment by MortenHofft** [comment]
The 500 from ant pro seem fine no? An inline with how we handle 403 
https://preview.pro.ant.design/exception/500

**Comment by MortenHofft** [comment]
blocking a request in dev tools throws an error (not a 500, but a site crash). We should handle network failures gracefully as well. For example as a popup showing you are offline (or simply the 500 stating it).

**Comment by luckyluck** [comment]
@MortenHofft, added some improvements. Now the user will see exception 500 but we can create a custom page for Network Error if we find a good icon for that.

**Comment by MortenHofft** [comment]
Perhaps we could just keep the icon and layout, but change the message  from `500 - Sorry, the server is reporting an error` to a message stating that there is a problem connecting to the server. Perhaps because the user is offline?
