### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#92]
The registry is largely working and have mostly feature parity with the prod version. But one thing is missing: error handling and feedback to the user.

At this point it would be useful to go through the app with the mindset that users are evil or stupid. 
Among other things that means:
* Cancelling requests that have a chance of updating the content "too late". 
* Give clear error messages.

See for example https://github.com/gbif/registry-console/issues/91

**Comment by luckyluck** [comment]
@MortenHofft, I added cancellation for every request I found suitable. Also, I added check on unmount to avoid mutation within unmounted components. As far as I see this practice is pretty common. Additionally, I refactored several requests for detail pages using Promise.all() - theoretically, it should give some performance benefits. 
If you have proposals or code notes, I'll keep this issue open.
