### ISSUE TITLE
headlines missing on search pages

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#93]
![screen shot 2018-12-21 at 10 22 46](https://user-images.githubusercontent.com/6759267/50335045-668f7400-050a-11e9-919b-afd7f6bf7b61.png)

We are missing headlines on search pages. Please add them along with a (?) with further help text

**Comment by luckyluck** [comment]
@MortenHofft, I added headlines on all list pages. Could you please clarify what text I should add with (?) for each item type?

**Comment by MortenHofft** [comment]
we might not need them. Could you please just add an example one for `/organization/nonPublishing` with the text: `Organizations that have not yet published any datasets`. Then we have an example of where such descriptions could go.
