### ISSUE TITLE
Create as site menu items

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#98]
I wonder if it would be nice to have all the creates in the menu. 
So a top level nav item called `+ Create new` that expands to show: `Organization, dataset, etc ...`

**Comment by luckyluck** [comment]
@MortenHofft, could you please clarify this enhancement? We have `Create new` buttons in the header.

**Comment by MortenHofft** [comment]
Yes we have them in the header of the search. This is just me posing the question if it would be convenient for the user to have the creates in the menu as well. But either way, I think that for now, it is better to focus on those issues that are not labelled as `enhancement`.
